/*
 * PTV Timetable API - Version 3
 *
 * The PTV Timetable API provides direct access to Public Transport Victoria's public transport timetable data.    The API returns scheduled timetable, route and stop data for all metropolitan and regional train, tram and bus services in Victoria, including Night Network(Night Train and Night Tram data are included in metropolitan train and tram services data, respectively, whereas Night Bus is a separate route type).    The API also returns real-time data for metropolitan train, tram and bus services (where this data is made available to PTV), as well as disruption information, stop facility information, and access to myki ticket outlet data.    This Swagger is for Version 3 of the PTV Timetable API. By using this documentation you agree to comply with the licence and terms of service.    Train timetable data is updated daily, while the remaining data is updated weekly, taking into account any planned timetable changes (for example, due to holidays or planned disruptions). The PTV timetable API is the same API used by PTV for its apps. To access the most up to date data PTV has (including real-time data) you must use the API dynamically.    You can access the PTV Timetable API through a HTTP or HTTPS interface, as follows:        base URL / version number / API name / query string  The base URL is either:    *  http://timetableapi.ptv.vic.gov.au  or    *  https://timetableapi.ptv.vic.gov.au    The Swagger JSON file is available at http://timetableapi.ptv.vic.gov.au/swagger/docs/v3    Frequently asked questions are available on the PTV website at http://ptv.vic.gov.au/apifaq    Links to the following information are also provided on the PTV website at http://ptv.vic.gov.au/ptv-timetable-api/  * How to register for an API key and calculate a signature  * PTV Timetable API V2 to V3 Migration Guide  * PTV Timetable API Data Quality Statement    All information about how to use the API is in this documentation. PTV cannot provide technical support for the API.  
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Ptv.Api.Client.Client.OpenAPIDateConverter;

namespace Ptv.Api.Client.Model
{
    /// <summary>
    /// V3Disruption
    /// </summary>
    [DataContract(Name = "V3.Disruption")]
    public partial class V3Disruption : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V3Disruption" /> class.
        /// </summary>
        /// <param name="disruptionId">Disruption information identifier.</param>
        /// <param name="title">Headline title summarising disruption information.</param>
        /// <param name="url">URL of relevant article on PTV website.</param>
        /// <param name="description">Description of the disruption.</param>
        /// <param name="disruptionStatus">Status of the disruption (e.g. \&quot;Planned\&quot;, \&quot;Current\&quot;).</param>
        /// <param name="disruptionType">Type of disruption.</param>
        /// <param name="publishedOn">Date and time disruption information is published on PTV website, in ISO 8601 UTC format.</param>
        /// <param name="lastUpdated">Date and time disruption information was last updated by PTV, in ISO 8601 UTC format.</param>
        /// <param name="fromDate">Date and time at which disruption begins, in ISO 8601 UTC format.</param>
        /// <param name="toDate">Date and time at which disruption ends, in ISO 8601 UTC format (returns null if unknown).</param>
        /// <param name="routes">Route relevant to a disruption (if applicable).</param>
        /// <param name="stops">Stop relevant to a disruption (if applicable).</param>
        /// <param name="colour">colour.</param>
        /// <param name="displayOnBoard">displayOnBoard.</param>
        /// <param name="displayStatus">displayStatus.</param>
        public V3Disruption(long disruptionId = default(long), string title = default(string), string url = default(string), string description = default(string), string disruptionStatus = default(string), string disruptionType = default(string), DateTime publishedOn = default(DateTime), DateTime lastUpdated = default(DateTime), DateTime fromDate = default(DateTime), DateTime toDate = default(DateTime), List<V3DisruptionRoute> routes = default(List<V3DisruptionRoute>), List<V3DisruptionStop> stops = default(List<V3DisruptionStop>), string colour = default(string), bool displayOnBoard = default(bool), bool displayStatus = default(bool))
        {
            this.DisruptionId = disruptionId;
            this.Title = title;
            this.Url = url;
            this.Description = description;
            this.DisruptionStatus = disruptionStatus;
            this.DisruptionType = disruptionType;
            this.PublishedOn = publishedOn;
            this.LastUpdated = lastUpdated;
            this.FromDate = fromDate;
            this.ToDate = toDate;
            this.Routes = routes;
            this.Stops = stops;
            this.Colour = colour;
            this.DisplayOnBoard = displayOnBoard;
            this.DisplayStatus = displayStatus;
        }

        /// <summary>
        /// Disruption information identifier
        /// </summary>
        /// <value>Disruption information identifier</value>
        [DataMember(Name = "disruption_id", EmitDefaultValue = false)]
        public long DisruptionId { get; set; }

        /// <summary>
        /// Headline title summarising disruption information
        /// </summary>
        /// <value>Headline title summarising disruption information</value>
        [DataMember(Name = "title", EmitDefaultValue = false)]
        public string Title { get; set; }

        /// <summary>
        /// URL of relevant article on PTV website
        /// </summary>
        /// <value>URL of relevant article on PTV website</value>
        [DataMember(Name = "url", EmitDefaultValue = false)]
        public string Url { get; set; }

        /// <summary>
        /// Description of the disruption
        /// </summary>
        /// <value>Description of the disruption</value>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Status of the disruption (e.g. \&quot;Planned\&quot;, \&quot;Current\&quot;)
        /// </summary>
        /// <value>Status of the disruption (e.g. \&quot;Planned\&quot;, \&quot;Current\&quot;)</value>
        [DataMember(Name = "disruption_status", EmitDefaultValue = false)]
        public string DisruptionStatus { get; set; }

        /// <summary>
        /// Type of disruption
        /// </summary>
        /// <value>Type of disruption</value>
        [DataMember(Name = "disruption_type", EmitDefaultValue = false)]
        public string DisruptionType { get; set; }

        /// <summary>
        /// Date and time disruption information is published on PTV website, in ISO 8601 UTC format
        /// </summary>
        /// <value>Date and time disruption information is published on PTV website, in ISO 8601 UTC format</value>
        [DataMember(Name = "published_on", EmitDefaultValue = false)]
        public DateTime PublishedOn { get; set; }

        /// <summary>
        /// Date and time disruption information was last updated by PTV, in ISO 8601 UTC format
        /// </summary>
        /// <value>Date and time disruption information was last updated by PTV, in ISO 8601 UTC format</value>
        [DataMember(Name = "last_updated", EmitDefaultValue = false)]
        public DateTime LastUpdated { get; set; }

        /// <summary>
        /// Date and time at which disruption begins, in ISO 8601 UTC format
        /// </summary>
        /// <value>Date and time at which disruption begins, in ISO 8601 UTC format</value>
        [DataMember(Name = "from_date", EmitDefaultValue = false)]
        public DateTime FromDate { get; set; }

        /// <summary>
        /// Date and time at which disruption ends, in ISO 8601 UTC format (returns null if unknown)
        /// </summary>
        /// <value>Date and time at which disruption ends, in ISO 8601 UTC format (returns null if unknown)</value>
        [DataMember(Name = "to_date", EmitDefaultValue = false)]
        public DateTime ToDate { get; set; }

        /// <summary>
        /// Route relevant to a disruption (if applicable)
        /// </summary>
        /// <value>Route relevant to a disruption (if applicable)</value>
        [DataMember(Name = "routes", EmitDefaultValue = false)]
        public List<V3DisruptionRoute> Routes { get; set; }

        /// <summary>
        /// Stop relevant to a disruption (if applicable)
        /// </summary>
        /// <value>Stop relevant to a disruption (if applicable)</value>
        [DataMember(Name = "stops", EmitDefaultValue = false)]
        public List<V3DisruptionStop> Stops { get; set; }

        /// <summary>
        /// Gets or Sets Colour
        /// </summary>
        [DataMember(Name = "colour", EmitDefaultValue = false)]
        public string Colour { get; set; }

        /// <summary>
        /// Gets or Sets DisplayOnBoard
        /// </summary>
        [DataMember(Name = "display_on_board", EmitDefaultValue = true)]
        public bool DisplayOnBoard { get; set; }

        /// <summary>
        /// Gets or Sets DisplayStatus
        /// </summary>
        [DataMember(Name = "display_status", EmitDefaultValue = true)]
        public bool DisplayStatus { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V3Disruption {\n");
            sb.Append("  DisruptionId: ").Append(DisruptionId).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  DisruptionStatus: ").Append(DisruptionStatus).Append("\n");
            sb.Append("  DisruptionType: ").Append(DisruptionType).Append("\n");
            sb.Append("  PublishedOn: ").Append(PublishedOn).Append("\n");
            sb.Append("  LastUpdated: ").Append(LastUpdated).Append("\n");
            sb.Append("  FromDate: ").Append(FromDate).Append("\n");
            sb.Append("  ToDate: ").Append(ToDate).Append("\n");
            sb.Append("  Routes: ").Append(Routes).Append("\n");
            sb.Append("  Stops: ").Append(Stops).Append("\n");
            sb.Append("  Colour: ").Append(Colour).Append("\n");
            sb.Append("  DisplayOnBoard: ").Append(DisplayOnBoard).Append("\n");
            sb.Append("  DisplayStatus: ").Append(DisplayStatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
