/*
 * PTV Timetable API - Version 3
 *
 * The PTV Timetable API provides direct access to Public Transport Victoria's public transport timetable data.    The API returns scheduled timetable, route and stop data for all metropolitan and regional train, tram and bus services in Victoria, including Night Network(Night Train and Night Tram data are included in metropolitan train and tram services data, respectively, whereas Night Bus is a separate route type).    The API also returns real-time data for metropolitan train, tram and bus services (where this data is made available to PTV), as well as disruption information, stop facility information, and access to myki ticket outlet data.    This Swagger is for Version 3 of the PTV Timetable API. By using this documentation you agree to comply with the licence and terms of service.    Train timetable data is updated daily, while the remaining data is updated weekly, taking into account any planned timetable changes (for example, due to holidays or planned disruptions). The PTV timetable API is the same API used by PTV for its apps. To access the most up to date data PTV has (including real-time data) you must use the API dynamically.    You can access the PTV Timetable API through a HTTP or HTTPS interface, as follows:        base URL / version number / API name / query string  The base URL is either:    *  http://timetableapi.ptv.vic.gov.au  or    *  https://timetableapi.ptv.vic.gov.au    The Swagger JSON file is available at http://timetableapi.ptv.vic.gov.au/swagger/docs/v3    Frequently asked questions are available on the PTV website at http://ptv.vic.gov.au/apifaq    Links to the following information are also provided on the PTV website at http://ptv.vic.gov.au/ptv-timetable-api/  * How to register for an API key and calculate a signature  * PTV Timetable API V2 to V3 Migration Guide  * PTV Timetable API Data Quality Statement    All information about how to use the API is in this documentation. PTV cannot provide technical support for the API.  
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Ptv.Api.Client.Client.OpenAPIDateConverter;

namespace Ptv.Api.Client.Model
{
    /// <summary>
    /// V3StopAccessibilityWheelchair
    /// </summary>
    [DataContract(Name = "V3.StopAccessibilityWheelchair")]
    public partial class V3StopAccessibilityWheelchair : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V3StopAccessibilityWheelchair" /> class.
        /// </summary>
        /// <param name="accessibleRamp">accessibleRamp.</param>
        /// <param name="parking">Indicates if there is at least one accessible parking spot at the stop that complies with the Disability Standards for Accessible Public Transport under the Disability Discrimination Act (1992).</param>
        /// <param name="telephone">Indicates if there is at least one accessible telephone at the stop/platform that complies with the Disability Standards for Accessible Public Transport under the Disability Discrimination Act (1992).</param>
        /// <param name="toilet">Indicates if there is at least one accessible toilet at the stop/platform that complies with the Disability Standards for Accessible Public Transport under the Disability Discrimination Act (1992).</param>
        /// <param name="lowTicketCounter">Indicates if there is at least one low ticket counter at the stop that complies with the Disability Standards for Accessible Public Transport under the Disability Discrimination Act (1992).</param>
        /// <param name="manouvering">Indicates if there is a space for mobility device to board on or off a transport mode.</param>
        /// <param name="raisedPlatform">Indicates if there is a raised platform to board a train.</param>
        /// <param name="ramp">Indicates if there are ramps (&amp;lt;1:14) at the stop/platform.</param>
        /// <param name="secondaryPath">Indicates if there is a path beyond the stop which is accessible.</param>
        /// <param name="raisedPlatformShelther">Indicates if there is shelter near the raised platform.</param>
        /// <param name="steepRamp">Indicates if there are ramps (&amp;gt;1:14) at the stop/platform.</param>
        public V3StopAccessibilityWheelchair(bool accessibleRamp = default(bool), bool parking = default(bool), bool telephone = default(bool), bool toilet = default(bool), bool lowTicketCounter = default(bool), bool manouvering = default(bool), bool raisedPlatform = default(bool), bool ramp = default(bool), bool secondaryPath = default(bool), bool raisedPlatformShelther = default(bool), bool steepRamp = default(bool))
        {
            this.AccessibleRamp = accessibleRamp;
            this.Parking = parking;
            this.Telephone = telephone;
            this.Toilet = toilet;
            this.LowTicketCounter = lowTicketCounter;
            this.Manouvering = manouvering;
            this.RaisedPlatform = raisedPlatform;
            this.Ramp = ramp;
            this.SecondaryPath = secondaryPath;
            this.RaisedPlatformShelther = raisedPlatformShelther;
            this.SteepRamp = steepRamp;
        }

        /// <summary>
        /// Gets or Sets AccessibleRamp
        /// </summary>
        [DataMember(Name = "accessible_ramp", EmitDefaultValue = true)]
        public bool AccessibleRamp { get; set; }

        /// <summary>
        /// Indicates if there is at least one accessible parking spot at the stop that complies with the Disability Standards for Accessible Public Transport under the Disability Discrimination Act (1992)
        /// </summary>
        /// <value>Indicates if there is at least one accessible parking spot at the stop that complies with the Disability Standards for Accessible Public Transport under the Disability Discrimination Act (1992)</value>
        [DataMember(Name = "parking", EmitDefaultValue = true)]
        public bool Parking { get; set; }

        /// <summary>
        /// Indicates if there is at least one accessible telephone at the stop/platform that complies with the Disability Standards for Accessible Public Transport under the Disability Discrimination Act (1992)
        /// </summary>
        /// <value>Indicates if there is at least one accessible telephone at the stop/platform that complies with the Disability Standards for Accessible Public Transport under the Disability Discrimination Act (1992)</value>
        [DataMember(Name = "telephone", EmitDefaultValue = true)]
        public bool Telephone { get; set; }

        /// <summary>
        /// Indicates if there is at least one accessible toilet at the stop/platform that complies with the Disability Standards for Accessible Public Transport under the Disability Discrimination Act (1992)
        /// </summary>
        /// <value>Indicates if there is at least one accessible toilet at the stop/platform that complies with the Disability Standards for Accessible Public Transport under the Disability Discrimination Act (1992)</value>
        [DataMember(Name = "toilet", EmitDefaultValue = true)]
        public bool Toilet { get; set; }

        /// <summary>
        /// Indicates if there is at least one low ticket counter at the stop that complies with the Disability Standards for Accessible Public Transport under the Disability Discrimination Act (1992)
        /// </summary>
        /// <value>Indicates if there is at least one low ticket counter at the stop that complies with the Disability Standards for Accessible Public Transport under the Disability Discrimination Act (1992)</value>
        [DataMember(Name = "low_ticket_counter", EmitDefaultValue = true)]
        public bool LowTicketCounter { get; set; }

        /// <summary>
        /// Indicates if there is a space for mobility device to board on or off a transport mode
        /// </summary>
        /// <value>Indicates if there is a space for mobility device to board on or off a transport mode</value>
        [DataMember(Name = "manouvering", EmitDefaultValue = true)]
        public bool Manouvering { get; set; }

        /// <summary>
        /// Indicates if there is a raised platform to board a train
        /// </summary>
        /// <value>Indicates if there is a raised platform to board a train</value>
        [DataMember(Name = "raised_platform", EmitDefaultValue = true)]
        public bool RaisedPlatform { get; set; }

        /// <summary>
        /// Indicates if there are ramps (&amp;lt;1:14) at the stop/platform
        /// </summary>
        /// <value>Indicates if there are ramps (&amp;lt;1:14) at the stop/platform</value>
        [DataMember(Name = "ramp", EmitDefaultValue = true)]
        public bool Ramp { get; set; }

        /// <summary>
        /// Indicates if there is a path beyond the stop which is accessible
        /// </summary>
        /// <value>Indicates if there is a path beyond the stop which is accessible</value>
        [DataMember(Name = "secondary_path", EmitDefaultValue = true)]
        public bool SecondaryPath { get; set; }

        /// <summary>
        /// Indicates if there is shelter near the raised platform
        /// </summary>
        /// <value>Indicates if there is shelter near the raised platform</value>
        [DataMember(Name = "raised_platform_shelther", EmitDefaultValue = true)]
        public bool RaisedPlatformShelther { get; set; }

        /// <summary>
        /// Indicates if there are ramps (&amp;gt;1:14) at the stop/platform
        /// </summary>
        /// <value>Indicates if there are ramps (&amp;gt;1:14) at the stop/platform</value>
        [DataMember(Name = "steep_ramp", EmitDefaultValue = true)]
        public bool SteepRamp { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V3StopAccessibilityWheelchair {\n");
            sb.Append("  AccessibleRamp: ").Append(AccessibleRamp).Append("\n");
            sb.Append("  Parking: ").Append(Parking).Append("\n");
            sb.Append("  Telephone: ").Append(Telephone).Append("\n");
            sb.Append("  Toilet: ").Append(Toilet).Append("\n");
            sb.Append("  LowTicketCounter: ").Append(LowTicketCounter).Append("\n");
            sb.Append("  Manouvering: ").Append(Manouvering).Append("\n");
            sb.Append("  RaisedPlatform: ").Append(RaisedPlatform).Append("\n");
            sb.Append("  Ramp: ").Append(Ramp).Append("\n");
            sb.Append("  SecondaryPath: ").Append(SecondaryPath).Append("\n");
            sb.Append("  RaisedPlatformShelther: ").Append(RaisedPlatformShelther).Append("\n");
            sb.Append("  SteepRamp: ").Append(SteepRamp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
