//
// V3DirectionWithDescription.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class V3DirectionWithDescription: JSONEncodable {
    public var routeDirectionDescription: String?
    /** Direction of travel identifier */
    public var directionId: Int32?
    /** Name of direction of travel */
    public var directionName: String?
    /** Route identifier */
    public var routeId: Int32?
    /** Transport mode identifier */
    public var routeType: Int32?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["route_direction_description"] = self.routeDirectionDescription
        nillableDictionary["direction_id"] = self.directionId?.encodeToJSON()
        nillableDictionary["direction_name"] = self.directionName
        nillableDictionary["route_id"] = self.routeId?.encodeToJSON()
        nillableDictionary["route_type"] = self.routeType?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
