/*
 * PTV Timetable API - Version 3
 * The PTV Timetable API provides direct access to Public Transport Victoria's public transport timetable data.    The API returns scheduled timetable, route and stop data for all metropolitan and regional train, tram and bus services in Victoria, including Night Network(Night Train and Night Tram data are included in metropolitan train and tram services data, respectively, whereas Night Bus is a separate route type).    The API also returns real-time data for metropolitan train, tram and bus services (where this data is made available to PTV), as well as disruption information, stop facility information, and access to myki ticket outlet data.    This Swagger is for Version 3 of the PTV Timetable API. By using this documentation you agree to comply with the licence and terms of service.    Train timetable data is updated daily, while the remaining data is updated weekly, taking into account any planned timetable changes (for example, due to holidays or planned disruptions). The PTV timetable API is the same API used by PTV for its apps. To access the most up to date data PTV has (including real-time data) you must use the API dynamically.    You can access the PTV Timetable API through a HTTP or HTTPS interface, as follows:        base URL / version number / API name / query string  The base URL is either:    *  http://timetableapi.ptv.vic.gov.au  or    *  https://timetableapi.ptv.vic.gov.au    The Swagger JSON file is available at http://timetableapi.ptv.vic.gov.au/swagger/docs/v3    Frequently asked questions are available on the PTV website at http://ptv.vic.gov.au/apifaq    Links to the following information are also provided on the PTV website at http://ptv.vic.gov.au/ptv-timetable-api/  * How to register for an API key and calculate a signature  * PTV Timetable API V2 to V3 Migration Guide  * PTV Timetable API Data Quality Statement    All information about how to use the API is in this documentation. PTV cannot provide technical support for the API.  
 *
 * OpenAPI spec version: v3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.52
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {V3StopModel} from './V3StopModel';

/**
 * The V3PatternDeparture model module.
 * @module model/V3PatternDeparture
 * @version v3
 */
export class V3PatternDeparture {
  /**
   * Constructs a new <code>V3PatternDeparture</code>.
   * @alias module:model/V3PatternDeparture
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>V3PatternDeparture</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V3PatternDeparture} obj Optional instance to populate.
   * @return {module:model/V3PatternDeparture} The populated <code>V3PatternDeparture</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new V3PatternDeparture();
      if (data.hasOwnProperty('skipped_stops'))
        obj.skippedStops = ApiClient.convertToType(data['skipped_stops'], [V3StopModel]);
      if (data.hasOwnProperty('stop_id'))
        obj.stopId = ApiClient.convertToType(data['stop_id'], 'Number');
      if (data.hasOwnProperty('route_id'))
        obj.routeId = ApiClient.convertToType(data['route_id'], 'Number');
      if (data.hasOwnProperty('run_id'))
        obj.runId = ApiClient.convertToType(data['run_id'], 'Number');
      if (data.hasOwnProperty('run_ref'))
        obj.runRef = ApiClient.convertToType(data['run_ref'], 'String');
      if (data.hasOwnProperty('direction_id'))
        obj.directionId = ApiClient.convertToType(data['direction_id'], 'Number');
      if (data.hasOwnProperty('disruption_ids'))
        obj.disruptionIds = ApiClient.convertToType(data['disruption_ids'], ['Number']);
      if (data.hasOwnProperty('scheduled_departure_utc'))
        obj.scheduledDepartureUtc = ApiClient.convertToType(data['scheduled_departure_utc'], 'Date');
      if (data.hasOwnProperty('estimated_departure_utc'))
        obj.estimatedDepartureUtc = ApiClient.convertToType(data['estimated_departure_utc'], 'Date');
      if (data.hasOwnProperty('at_platform'))
        obj.atPlatform = ApiClient.convertToType(data['at_platform'], 'Boolean');
      if (data.hasOwnProperty('platform_number'))
        obj.platformNumber = ApiClient.convertToType(data['platform_number'], 'String');
      if (data.hasOwnProperty('flags'))
        obj.flags = ApiClient.convertToType(data['flags'], 'String');
      if (data.hasOwnProperty('departure_sequence'))
        obj.departureSequence = ApiClient.convertToType(data['departure_sequence'], 'Number');
    }
    return obj;
  }
}

/**
 * The stops to be skipped following the current departure in order.
 * @member {Array.<module:model/V3StopModel>} skippedStops
 */
V3PatternDeparture.prototype.skippedStops = undefined;

/**
 * Stop identifier
 * @member {Number} stopId
 */
V3PatternDeparture.prototype.stopId = undefined;

/**
 * Route identifier
 * @member {Number} routeId
 */
V3PatternDeparture.prototype.routeId = undefined;

/**
 * Numeric trip/service run identifier. Defaults to -1 when run identifier is Alphanumeric
 * @member {Number} runId
 */
V3PatternDeparture.prototype.runId = undefined;

/**
 * Alphanumeric trip/service run identifier
 * @member {String} runRef
 */
V3PatternDeparture.prototype.runRef = undefined;

/**
 * Direction of travel identifier
 * @member {Number} directionId
 */
V3PatternDeparture.prototype.directionId = undefined;

/**
 * Disruption information identifier(s)
 * @member {Array.<Number>} disruptionIds
 */
V3PatternDeparture.prototype.disruptionIds = undefined;

/**
 * Scheduled (i.e. timetabled) departure time and date in ISO 8601 UTC format
 * @member {Date} scheduledDepartureUtc
 */
V3PatternDeparture.prototype.scheduledDepartureUtc = undefined;

/**
 * Real-time estimate of departure time and date in ISO 8601 UTC format
 * @member {Date} estimatedDepartureUtc
 */
V3PatternDeparture.prototype.estimatedDepartureUtc = undefined;

/**
 * Indicates if the metropolitan train service is at the platform at the time of query; returns false for other modes
 * @member {Boolean} atPlatform
 */
V3PatternDeparture.prototype.atPlatform = undefined;

/**
 * Platform number at stop (metropolitan train only; returns null for other modes)
 * @member {String} platformNumber
 */
V3PatternDeparture.prototype.platformNumber = undefined;

/**
 * Flag indicating special condition for run (e.g. RR Reservations Required, GC Guaranteed Connection, DOO Drop Off Only, PUO Pick Up Only, MO Mondays only, TU Tuesdays only, WE Wednesdays only, TH Thursdays only, FR Fridays only, SS School days only; ignore E flag)
 * @member {String} flags
 */
V3PatternDeparture.prototype.flags = undefined;

/**
 * Chronological sequence for the departures in a run. Order ascendingly by this field to get chronological order (earliest first) of departures with the same run_ref. NOTE, this field is not always N+1 or N-1 of the previous or following departure. e.g 100, 200, 250, 300 instead of 1, 2, 3, 4
 * @member {Number} departureSequence
 */
V3PatternDeparture.prototype.departureSequence = undefined;

