# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class V3DisruptionMode(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, disruption_mode_name: str=None, disruption_mode: int=None):  # noqa: E501
        """V3DisruptionMode - a model defined in Swagger

        :param disruption_mode_name: The disruption_mode_name of this V3DisruptionMode.  # noqa: E501
        :type disruption_mode_name: str
        :param disruption_mode: The disruption_mode of this V3DisruptionMode.  # noqa: E501
        :type disruption_mode: int
        """
        self.swagger_types = {
            'disruption_mode_name': str,
            'disruption_mode': int
        }

        self.attribute_map = {
            'disruption_mode_name': 'disruption_mode_name',
            'disruption_mode': 'disruption_mode'
        }
        self._disruption_mode_name = disruption_mode_name
        self._disruption_mode = disruption_mode

    @classmethod
    def from_dict(cls, dikt) -> 'V3DisruptionMode':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The V3.DisruptionMode of this V3DisruptionMode.  # noqa: E501
        :rtype: V3DisruptionMode
        """
        return util.deserialize_model(dikt, cls)

    @property
    def disruption_mode_name(self) -> str:
        """Gets the disruption_mode_name of this V3DisruptionMode.

        Name of disruption mode  # noqa: E501

        :return: The disruption_mode_name of this V3DisruptionMode.
        :rtype: str
        """
        return self._disruption_mode_name

    @disruption_mode_name.setter
    def disruption_mode_name(self, disruption_mode_name: str):
        """Sets the disruption_mode_name of this V3DisruptionMode.

        Name of disruption mode  # noqa: E501

        :param disruption_mode_name: The disruption_mode_name of this V3DisruptionMode.
        :type disruption_mode_name: str
        """

        self._disruption_mode_name = disruption_mode_name

    @property
    def disruption_mode(self) -> int:
        """Gets the disruption_mode of this V3DisruptionMode.

        Disruption mode identifier  # noqa: E501

        :return: The disruption_mode of this V3DisruptionMode.
        :rtype: int
        """
        return self._disruption_mode

    @disruption_mode.setter
    def disruption_mode(self, disruption_mode: int):
        """Sets the disruption_mode of this V3DisruptionMode.

        Disruption mode identifier  # noqa: E501

        :param disruption_mode: The disruption_mode of this V3DisruptionMode.
        :type disruption_mode: int
        """

        self._disruption_mode = disruption_mode
