# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class V3DisruptionStop(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, stop_id: int=None, stop_name: str=None):  # noqa: E501
        """V3DisruptionStop - a model defined in Swagger

        :param stop_id: The stop_id of this V3DisruptionStop.  # noqa: E501
        :type stop_id: int
        :param stop_name: The stop_name of this V3DisruptionStop.  # noqa: E501
        :type stop_name: str
        """
        self.swagger_types = {
            'stop_id': int,
            'stop_name': str
        }

        self.attribute_map = {
            'stop_id': 'stop_id',
            'stop_name': 'stop_name'
        }
        self._stop_id = stop_id
        self._stop_name = stop_name

    @classmethod
    def from_dict(cls, dikt) -> 'V3DisruptionStop':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The V3.DisruptionStop of this V3DisruptionStop.  # noqa: E501
        :rtype: V3DisruptionStop
        """
        return util.deserialize_model(dikt, cls)

    @property
    def stop_id(self) -> int:
        """Gets the stop_id of this V3DisruptionStop.


        :return: The stop_id of this V3DisruptionStop.
        :rtype: int
        """
        return self._stop_id

    @stop_id.setter
    def stop_id(self, stop_id: int):
        """Sets the stop_id of this V3DisruptionStop.


        :param stop_id: The stop_id of this V3DisruptionStop.
        :type stop_id: int
        """

        self._stop_id = stop_id

    @property
    def stop_name(self) -> str:
        """Gets the stop_name of this V3DisruptionStop.


        :return: The stop_name of this V3DisruptionStop.
        :rtype: str
        """
        return self._stop_name

    @stop_name.setter
    def stop_name(self, stop_name: str):
        """Sets the stop_name of this V3DisruptionStop.


        :param stop_name: The stop_name of this V3DisruptionStop.
        :type stop_name: str
        """

        self._stop_name = stop_name
