# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.v3_stop_model import V3StopModel  # noqa: F401,E501
from swagger_server import util


class V3PatternDeparture(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, skipped_stops: List[V3StopModel]=None, stop_id: int=None, route_id: int=None, run_id: int=None, run_ref: str=None, direction_id: int=None, disruption_ids: List[int]=None, scheduled_departure_utc: datetime=None, estimated_departure_utc: datetime=None, at_platform: bool=None, platform_number: str=None, flags: str=None, departure_sequence: int=None):  # noqa: E501
        """V3PatternDeparture - a model defined in Swagger

        :param skipped_stops: The skipped_stops of this V3PatternDeparture.  # noqa: E501
        :type skipped_stops: List[V3StopModel]
        :param stop_id: The stop_id of this V3PatternDeparture.  # noqa: E501
        :type stop_id: int
        :param route_id: The route_id of this V3PatternDeparture.  # noqa: E501
        :type route_id: int
        :param run_id: The run_id of this V3PatternDeparture.  # noqa: E501
        :type run_id: int
        :param run_ref: The run_ref of this V3PatternDeparture.  # noqa: E501
        :type run_ref: str
        :param direction_id: The direction_id of this V3PatternDeparture.  # noqa: E501
        :type direction_id: int
        :param disruption_ids: The disruption_ids of this V3PatternDeparture.  # noqa: E501
        :type disruption_ids: List[int]
        :param scheduled_departure_utc: The scheduled_departure_utc of this V3PatternDeparture.  # noqa: E501
        :type scheduled_departure_utc: datetime
        :param estimated_departure_utc: The estimated_departure_utc of this V3PatternDeparture.  # noqa: E501
        :type estimated_departure_utc: datetime
        :param at_platform: The at_platform of this V3PatternDeparture.  # noqa: E501
        :type at_platform: bool
        :param platform_number: The platform_number of this V3PatternDeparture.  # noqa: E501
        :type platform_number: str
        :param flags: The flags of this V3PatternDeparture.  # noqa: E501
        :type flags: str
        :param departure_sequence: The departure_sequence of this V3PatternDeparture.  # noqa: E501
        :type departure_sequence: int
        """
        self.swagger_types = {
            'skipped_stops': List[V3StopModel],
            'stop_id': int,
            'route_id': int,
            'run_id': int,
            'run_ref': str,
            'direction_id': int,
            'disruption_ids': List[int],
            'scheduled_departure_utc': datetime,
            'estimated_departure_utc': datetime,
            'at_platform': bool,
            'platform_number': str,
            'flags': str,
            'departure_sequence': int
        }

        self.attribute_map = {
            'skipped_stops': 'skipped_stops',
            'stop_id': 'stop_id',
            'route_id': 'route_id',
            'run_id': 'run_id',
            'run_ref': 'run_ref',
            'direction_id': 'direction_id',
            'disruption_ids': 'disruption_ids',
            'scheduled_departure_utc': 'scheduled_departure_utc',
            'estimated_departure_utc': 'estimated_departure_utc',
            'at_platform': 'at_platform',
            'platform_number': 'platform_number',
            'flags': 'flags',
            'departure_sequence': 'departure_sequence'
        }
        self._skipped_stops = skipped_stops
        self._stop_id = stop_id
        self._route_id = route_id
        self._run_id = run_id
        self._run_ref = run_ref
        self._direction_id = direction_id
        self._disruption_ids = disruption_ids
        self._scheduled_departure_utc = scheduled_departure_utc
        self._estimated_departure_utc = estimated_departure_utc
        self._at_platform = at_platform
        self._platform_number = platform_number
        self._flags = flags
        self._departure_sequence = departure_sequence

    @classmethod
    def from_dict(cls, dikt) -> 'V3PatternDeparture':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The V3.PatternDeparture of this V3PatternDeparture.  # noqa: E501
        :rtype: V3PatternDeparture
        """
        return util.deserialize_model(dikt, cls)

    @property
    def skipped_stops(self) -> List[V3StopModel]:
        """Gets the skipped_stops of this V3PatternDeparture.

        The stops to be skipped following the current departure in order.  # noqa: E501

        :return: The skipped_stops of this V3PatternDeparture.
        :rtype: List[V3StopModel]
        """
        return self._skipped_stops

    @skipped_stops.setter
    def skipped_stops(self, skipped_stops: List[V3StopModel]):
        """Sets the skipped_stops of this V3PatternDeparture.

        The stops to be skipped following the current departure in order.  # noqa: E501

        :param skipped_stops: The skipped_stops of this V3PatternDeparture.
        :type skipped_stops: List[V3StopModel]
        """

        self._skipped_stops = skipped_stops

    @property
    def stop_id(self) -> int:
        """Gets the stop_id of this V3PatternDeparture.

        Stop identifier  # noqa: E501

        :return: The stop_id of this V3PatternDeparture.
        :rtype: int
        """
        return self._stop_id

    @stop_id.setter
    def stop_id(self, stop_id: int):
        """Sets the stop_id of this V3PatternDeparture.

        Stop identifier  # noqa: E501

        :param stop_id: The stop_id of this V3PatternDeparture.
        :type stop_id: int
        """

        self._stop_id = stop_id

    @property
    def route_id(self) -> int:
        """Gets the route_id of this V3PatternDeparture.

        Route identifier  # noqa: E501

        :return: The route_id of this V3PatternDeparture.
        :rtype: int
        """
        return self._route_id

    @route_id.setter
    def route_id(self, route_id: int):
        """Sets the route_id of this V3PatternDeparture.

        Route identifier  # noqa: E501

        :param route_id: The route_id of this V3PatternDeparture.
        :type route_id: int
        """

        self._route_id = route_id

    @property
    def run_id(self) -> int:
        """Gets the run_id of this V3PatternDeparture.

        Numeric trip/service run identifier. Defaults to -1 when run identifier is Alphanumeric  # noqa: E501

        :return: The run_id of this V3PatternDeparture.
        :rtype: int
        """
        return self._run_id

    @run_id.setter
    def run_id(self, run_id: int):
        """Sets the run_id of this V3PatternDeparture.

        Numeric trip/service run identifier. Defaults to -1 when run identifier is Alphanumeric  # noqa: E501

        :param run_id: The run_id of this V3PatternDeparture.
        :type run_id: int
        """

        self._run_id = run_id

    @property
    def run_ref(self) -> str:
        """Gets the run_ref of this V3PatternDeparture.

        Alphanumeric trip/service run identifier  # noqa: E501

        :return: The run_ref of this V3PatternDeparture.
        :rtype: str
        """
        return self._run_ref

    @run_ref.setter
    def run_ref(self, run_ref: str):
        """Sets the run_ref of this V3PatternDeparture.

        Alphanumeric trip/service run identifier  # noqa: E501

        :param run_ref: The run_ref of this V3PatternDeparture.
        :type run_ref: str
        """

        self._run_ref = run_ref

    @property
    def direction_id(self) -> int:
        """Gets the direction_id of this V3PatternDeparture.

        Direction of travel identifier  # noqa: E501

        :return: The direction_id of this V3PatternDeparture.
        :rtype: int
        """
        return self._direction_id

    @direction_id.setter
    def direction_id(self, direction_id: int):
        """Sets the direction_id of this V3PatternDeparture.

        Direction of travel identifier  # noqa: E501

        :param direction_id: The direction_id of this V3PatternDeparture.
        :type direction_id: int
        """

        self._direction_id = direction_id

    @property
    def disruption_ids(self) -> List[int]:
        """Gets the disruption_ids of this V3PatternDeparture.

        Disruption information identifier(s)  # noqa: E501

        :return: The disruption_ids of this V3PatternDeparture.
        :rtype: List[int]
        """
        return self._disruption_ids

    @disruption_ids.setter
    def disruption_ids(self, disruption_ids: List[int]):
        """Sets the disruption_ids of this V3PatternDeparture.

        Disruption information identifier(s)  # noqa: E501

        :param disruption_ids: The disruption_ids of this V3PatternDeparture.
        :type disruption_ids: List[int]
        """

        self._disruption_ids = disruption_ids

    @property
    def scheduled_departure_utc(self) -> datetime:
        """Gets the scheduled_departure_utc of this V3PatternDeparture.

        Scheduled (i.e. timetabled) departure time and date in ISO 8601 UTC format  # noqa: E501

        :return: The scheduled_departure_utc of this V3PatternDeparture.
        :rtype: datetime
        """
        return self._scheduled_departure_utc

    @scheduled_departure_utc.setter
    def scheduled_departure_utc(self, scheduled_departure_utc: datetime):
        """Sets the scheduled_departure_utc of this V3PatternDeparture.

        Scheduled (i.e. timetabled) departure time and date in ISO 8601 UTC format  # noqa: E501

        :param scheduled_departure_utc: The scheduled_departure_utc of this V3PatternDeparture.
        :type scheduled_departure_utc: datetime
        """

        self._scheduled_departure_utc = scheduled_departure_utc

    @property
    def estimated_departure_utc(self) -> datetime:
        """Gets the estimated_departure_utc of this V3PatternDeparture.

        Real-time estimate of departure time and date in ISO 8601 UTC format  # noqa: E501

        :return: The estimated_departure_utc of this V3PatternDeparture.
        :rtype: datetime
        """
        return self._estimated_departure_utc

    @estimated_departure_utc.setter
    def estimated_departure_utc(self, estimated_departure_utc: datetime):
        """Sets the estimated_departure_utc of this V3PatternDeparture.

        Real-time estimate of departure time and date in ISO 8601 UTC format  # noqa: E501

        :param estimated_departure_utc: The estimated_departure_utc of this V3PatternDeparture.
        :type estimated_departure_utc: datetime
        """

        self._estimated_departure_utc = estimated_departure_utc

    @property
    def at_platform(self) -> bool:
        """Gets the at_platform of this V3PatternDeparture.

        Indicates if the metropolitan train service is at the platform at the time of query; returns false for other modes  # noqa: E501

        :return: The at_platform of this V3PatternDeparture.
        :rtype: bool
        """
        return self._at_platform

    @at_platform.setter
    def at_platform(self, at_platform: bool):
        """Sets the at_platform of this V3PatternDeparture.

        Indicates if the metropolitan train service is at the platform at the time of query; returns false for other modes  # noqa: E501

        :param at_platform: The at_platform of this V3PatternDeparture.
        :type at_platform: bool
        """

        self._at_platform = at_platform

    @property
    def platform_number(self) -> str:
        """Gets the platform_number of this V3PatternDeparture.

        Platform number at stop (metropolitan train only; returns null for other modes)  # noqa: E501

        :return: The platform_number of this V3PatternDeparture.
        :rtype: str
        """
        return self._platform_number

    @platform_number.setter
    def platform_number(self, platform_number: str):
        """Sets the platform_number of this V3PatternDeparture.

        Platform number at stop (metropolitan train only; returns null for other modes)  # noqa: E501

        :param platform_number: The platform_number of this V3PatternDeparture.
        :type platform_number: str
        """

        self._platform_number = platform_number

    @property
    def flags(self) -> str:
        """Gets the flags of this V3PatternDeparture.

        Flag indicating special condition for run (e.g. RR Reservations Required, GC Guaranteed Connection, DOO Drop Off Only, PUO Pick Up Only, MO Mondays only, TU Tuesdays only, WE Wednesdays only, TH Thursdays only, FR Fridays only, SS School days only; ignore E flag)  # noqa: E501

        :return: The flags of this V3PatternDeparture.
        :rtype: str
        """
        return self._flags

    @flags.setter
    def flags(self, flags: str):
        """Sets the flags of this V3PatternDeparture.

        Flag indicating special condition for run (e.g. RR Reservations Required, GC Guaranteed Connection, DOO Drop Off Only, PUO Pick Up Only, MO Mondays only, TU Tuesdays only, WE Wednesdays only, TH Thursdays only, FR Fridays only, SS School days only; ignore E flag)  # noqa: E501

        :param flags: The flags of this V3PatternDeparture.
        :type flags: str
        """

        self._flags = flags

    @property
    def departure_sequence(self) -> int:
        """Gets the departure_sequence of this V3PatternDeparture.

        Chronological sequence for the departures in a run. Order ascendingly by this field to get chronological order (earliest first) of departures with the same run_ref. NOTE, this field is not always N+1 or N-1 of the previous or following departure. e.g 100, 200, 250, 300 instead of 1, 2, 3, 4  # noqa: E501

        :return: The departure_sequence of this V3PatternDeparture.
        :rtype: int
        """
        return self._departure_sequence

    @departure_sequence.setter
    def departure_sequence(self, departure_sequence: int):
        """Sets the departure_sequence of this V3PatternDeparture.

        Chronological sequence for the departures in a run. Order ascendingly by this field to get chronological order (earliest first) of departures with the same run_ref. NOTE, this field is not always N+1 or N-1 of the previous or following departure. e.g 100, 200, 250, 300 instead of 1, 2, 3, 4  # noqa: E501

        :param departure_sequence: The departure_sequence of this V3PatternDeparture.
        :type departure_sequence: int
        """

        self._departure_sequence = departure_sequence
