# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.v3_stop_departure_request_route_direction import V3StopDepartureRequestRouteDirection  # noqa: F401,E501
from swagger_server import util


class V3StopDepartureRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, route_type: int=None, stop_id: int=None, max_results: int=None, gtfs: bool=None, route_directions: List[V3StopDepartureRequestRouteDirection]=None):  # noqa: E501
        """V3StopDepartureRequest - a model defined in Swagger

        :param route_type: The route_type of this V3StopDepartureRequest.  # noqa: E501
        :type route_type: int
        :param stop_id: The stop_id of this V3StopDepartureRequest.  # noqa: E501
        :type stop_id: int
        :param max_results: The max_results of this V3StopDepartureRequest.  # noqa: E501
        :type max_results: int
        :param gtfs: The gtfs of this V3StopDepartureRequest.  # noqa: E501
        :type gtfs: bool
        :param route_directions: The route_directions of this V3StopDepartureRequest.  # noqa: E501
        :type route_directions: List[V3StopDepartureRequestRouteDirection]
        """
        self.swagger_types = {
            'route_type': int,
            'stop_id': int,
            'max_results': int,
            'gtfs': bool,
            'route_directions': List[V3StopDepartureRequestRouteDirection]
        }

        self.attribute_map = {
            'route_type': 'route_type',
            'stop_id': 'stop_id',
            'max_results': 'max_results',
            'gtfs': 'gtfs',
            'route_directions': 'route_directions'
        }
        self._route_type = route_type
        self._stop_id = stop_id
        self._max_results = max_results
        self._gtfs = gtfs
        self._route_directions = route_directions

    @classmethod
    def from_dict(cls, dikt) -> 'V3StopDepartureRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The V3.StopDepartureRequest of this V3StopDepartureRequest.  # noqa: E501
        :rtype: V3StopDepartureRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def route_type(self) -> int:
        """Gets the route_type of this V3StopDepartureRequest.

        Number identifying transport mode; values returned via RouteTypes API  # noqa: E501

        :return: The route_type of this V3StopDepartureRequest.
        :rtype: int
        """
        return self._route_type

    @route_type.setter
    def route_type(self, route_type: int):
        """Sets the route_type of this V3StopDepartureRequest.

        Number identifying transport mode; values returned via RouteTypes API  # noqa: E501

        :param route_type: The route_type of this V3StopDepartureRequest.
        :type route_type: int
        """
        allowed_values = ["0", "1", "2", "3", "4"]  # noqa: E501
        if route_type not in allowed_values:
            raise ValueError(
                "Invalid value for `route_type` ({0}), must be one of {1}"
                .format(route_type, allowed_values)
            )

        self._route_type = route_type

    @property
    def stop_id(self) -> int:
        """Gets the stop_id of this V3StopDepartureRequest.

        Identifier of stop; values returned by Stops API  # noqa: E501

        :return: The stop_id of this V3StopDepartureRequest.
        :rtype: int
        """
        return self._stop_id

    @stop_id.setter
    def stop_id(self, stop_id: int):
        """Sets the stop_id of this V3StopDepartureRequest.

        Identifier of stop; values returned by Stops API  # noqa: E501

        :param stop_id: The stop_id of this V3StopDepartureRequest.
        :type stop_id: int
        """

        self._stop_id = stop_id

    @property
    def max_results(self) -> int:
        """Gets the max_results of this V3StopDepartureRequest.

        Maximum number of results returned  # noqa: E501

        :return: The max_results of this V3StopDepartureRequest.
        :rtype: int
        """
        return self._max_results

    @max_results.setter
    def max_results(self, max_results: int):
        """Sets the max_results of this V3StopDepartureRequest.

        Maximum number of results returned  # noqa: E501

        :param max_results: The max_results of this V3StopDepartureRequest.
        :type max_results: int
        """

        self._max_results = max_results

    @property
    def gtfs(self) -> bool:
        """Gets the gtfs of this V3StopDepartureRequest.

        Indicates that stop_id parameter will accept \"GTFS stop_id\" data and route_directions[x].route_id parameters will accept route_gtfs_id data  # noqa: E501

        :return: The gtfs of this V3StopDepartureRequest.
        :rtype: bool
        """
        return self._gtfs

    @gtfs.setter
    def gtfs(self, gtfs: bool):
        """Sets the gtfs of this V3StopDepartureRequest.

        Indicates that stop_id parameter will accept \"GTFS stop_id\" data and route_directions[x].route_id parameters will accept route_gtfs_id data  # noqa: E501

        :param gtfs: The gtfs of this V3StopDepartureRequest.
        :type gtfs: bool
        """

        self._gtfs = gtfs

    @property
    def route_directions(self) -> List[V3StopDepartureRequestRouteDirection]:
        """Gets the route_directions of this V3StopDepartureRequest.

        The route directions to find departures for at this stop.  # noqa: E501

        :return: The route_directions of this V3StopDepartureRequest.
        :rtype: List[V3StopDepartureRequestRouteDirection]
        """
        return self._route_directions

    @route_directions.setter
    def route_directions(self, route_directions: List[V3StopDepartureRequestRouteDirection]):
        """Sets the route_directions of this V3StopDepartureRequest.

        The route directions to find departures for at this stop.  # noqa: E501

        :param route_directions: The route_directions of this V3StopDepartureRequest.
        :type route_directions: List[V3StopDepartureRequestRouteDirection]
        """
        if route_directions is None:
            raise ValueError("Invalid value for `route_directions`, must not be `None`")  # noqa: E501

        self._route_directions = route_directions
