# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class V3SiriSubscriptionTopic(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, line_ref: str=None, direction_ref: int=None, route_type: int=None):  # noqa: E501
        """V3SiriSubscriptionTopic - a model defined in Swagger

        :param line_ref: The line_ref of this V3SiriSubscriptionTopic.  # noqa: E501
        :type line_ref: str
        :param direction_ref: The direction_ref of this V3SiriSubscriptionTopic.  # noqa: E501
        :type direction_ref: int
        :param route_type: The route_type of this V3SiriSubscriptionTopic.  # noqa: E501
        :type route_type: int
        """
        self.swagger_types = {
            'line_ref': str,
            'direction_ref': int,
            'route_type': int
        }

        self.attribute_map = {
            'line_ref': 'line_ref',
            'direction_ref': 'direction_ref',
            'route_type': 'route_type'
        }
        self._line_ref = line_ref
        self._direction_ref = direction_ref
        self._route_type = route_type

    @classmethod
    def from_dict(cls, dikt) -> 'V3SiriSubscriptionTopic':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The V3.SiriSubscriptionTopic of this V3SiriSubscriptionTopic.  # noqa: E501
        :rtype: V3SiriSubscriptionTopic
        """
        return util.deserialize_model(dikt, cls)

    @property
    def line_ref(self) -> str:
        """Gets the line_ref of this V3SiriSubscriptionTopic.

        Siri LineRef  # noqa: E501

        :return: The line_ref of this V3SiriSubscriptionTopic.
        :rtype: str
        """
        return self._line_ref

    @line_ref.setter
    def line_ref(self, line_ref: str):
        """Sets the line_ref of this V3SiriSubscriptionTopic.

        Siri LineRef  # noqa: E501

        :param line_ref: The line_ref of this V3SiriSubscriptionTopic.
        :type line_ref: str
        """
        if line_ref is None:
            raise ValueError("Invalid value for `line_ref`, must not be `None`")  # noqa: E501

        self._line_ref = line_ref

    @property
    def direction_ref(self) -> int:
        """Gets the direction_ref of this V3SiriSubscriptionTopic.

        Siri DirectionRef  (in, out, up, down, clockwise, counterclockwise, Inbound, Outbound)  # noqa: E501

        :return: The direction_ref of this V3SiriSubscriptionTopic.
        :rtype: int
        """
        return self._direction_ref

    @direction_ref.setter
    def direction_ref(self, direction_ref: int):
        """Sets the direction_ref of this V3SiriSubscriptionTopic.

        Siri DirectionRef  (in, out, up, down, clockwise, counterclockwise, Inbound, Outbound)  # noqa: E501

        :param direction_ref: The direction_ref of this V3SiriSubscriptionTopic.
        :type direction_ref: int
        """
        allowed_values = ["1", "2", "5", "10", "16", "32", "65", "130"]  # noqa: E501
        if direction_ref not in allowed_values:
            raise ValueError(
                "Invalid value for `direction_ref` ({0}), must be one of {1}"
                .format(direction_ref, allowed_values)
            )

        self._direction_ref = direction_ref

    @property
    def route_type(self) -> int:
        """Gets the route_type of this V3SiriSubscriptionTopic.

        Route Type eg. 0 (Train) 1 (Tram) 2 (Bus) 3 (Vline) 4 (NightRider)  # noqa: E501

        :return: The route_type of this V3SiriSubscriptionTopic.
        :rtype: int
        """
        return self._route_type

    @route_type.setter
    def route_type(self, route_type: int):
        """Sets the route_type of this V3SiriSubscriptionTopic.

        Route Type eg. 0 (Train) 1 (Tram) 2 (Bus) 3 (Vline) 4 (NightRider)  # noqa: E501

        :param route_type: The route_type of this V3SiriSubscriptionTopic.
        :type route_type: int
        """
        allowed_values = ["0", "1", "2", "3", "4"]  # noqa: E501
        if route_type not in allowed_values:
            raise ValueError(
                "Invalid value for `route_type` ({0}), must be one of {1}"
                .format(route_type, allowed_values)
            )

        self._route_type = route_type
