# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.v3_siri_direction_refs_dictionary import V3SiriDirectionRefsDictionary  # noqa: F401,E501
from swagger_server.models.v3_status import V3Status  # noqa: F401,E501
from swagger_server.models.v3_stop_point import V3StopPoint  # noqa: F401,E501
from swagger_server import util


class V3SiriReferenceDataMappingsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, mapping_version: str=None, line_refs: Dict[str, V3SiriDirectionRefsDictionary]=None, stop_point_refs: Dict[str, V3StopPoint]=None, status: V3Status=None):  # noqa: E501
        """V3SiriReferenceDataMappingsResponse - a model defined in Swagger

        :param mapping_version: The mapping_version of this V3SiriReferenceDataMappingsResponse.  # noqa: E501
        :type mapping_version: str
        :param line_refs: The line_refs of this V3SiriReferenceDataMappingsResponse.  # noqa: E501
        :type line_refs: Dict[str, V3SiriDirectionRefsDictionary]
        :param stop_point_refs: The stop_point_refs of this V3SiriReferenceDataMappingsResponse.  # noqa: E501
        :type stop_point_refs: Dict[str, V3StopPoint]
        :param status: The status of this V3SiriReferenceDataMappingsResponse.  # noqa: E501
        :type status: V3Status
        """
        self.swagger_types = {
            'mapping_version': str,
            'line_refs': Dict[str, V3SiriDirectionRefsDictionary],
            'stop_point_refs': Dict[str, V3StopPoint],
            'status': V3Status
        }

        self.attribute_map = {
            'mapping_version': 'mapping_version',
            'line_refs': 'line_refs',
            'stop_point_refs': 'stop_point_refs',
            'status': 'status'
        }
        self._mapping_version = mapping_version
        self._line_refs = line_refs
        self._stop_point_refs = stop_point_refs
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'V3SiriReferenceDataMappingsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The V3.SiriReferenceDataMappingsResponse of this V3SiriReferenceDataMappingsResponse.  # noqa: E501
        :rtype: V3SiriReferenceDataMappingsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def mapping_version(self) -> str:
        """Gets the mapping_version of this V3SiriReferenceDataMappingsResponse.


        :return: The mapping_version of this V3SiriReferenceDataMappingsResponse.
        :rtype: str
        """
        return self._mapping_version

    @mapping_version.setter
    def mapping_version(self, mapping_version: str):
        """Sets the mapping_version of this V3SiriReferenceDataMappingsResponse.


        :param mapping_version: The mapping_version of this V3SiriReferenceDataMappingsResponse.
        :type mapping_version: str
        """

        self._mapping_version = mapping_version

    @property
    def line_refs(self) -> Dict[str, V3SiriDirectionRefsDictionary]:
        """Gets the line_refs of this V3SiriReferenceDataMappingsResponse.

        SIRI LineRef  # noqa: E501

        :return: The line_refs of this V3SiriReferenceDataMappingsResponse.
        :rtype: Dict[str, V3SiriDirectionRefsDictionary]
        """
        return self._line_refs

    @line_refs.setter
    def line_refs(self, line_refs: Dict[str, V3SiriDirectionRefsDictionary]):
        """Sets the line_refs of this V3SiriReferenceDataMappingsResponse.

        SIRI LineRef  # noqa: E501

        :param line_refs: The line_refs of this V3SiriReferenceDataMappingsResponse.
        :type line_refs: Dict[str, V3SiriDirectionRefsDictionary]
        """

        self._line_refs = line_refs

    @property
    def stop_point_refs(self) -> Dict[str, V3StopPoint]:
        """Gets the stop_point_refs of this V3SiriReferenceDataMappingsResponse.


        :return: The stop_point_refs of this V3SiriReferenceDataMappingsResponse.
        :rtype: Dict[str, V3StopPoint]
        """
        return self._stop_point_refs

    @stop_point_refs.setter
    def stop_point_refs(self, stop_point_refs: Dict[str, V3StopPoint]):
        """Sets the stop_point_refs of this V3SiriReferenceDataMappingsResponse.


        :param stop_point_refs: The stop_point_refs of this V3SiriReferenceDataMappingsResponse.
        :type stop_point_refs: Dict[str, V3StopPoint]
        """

        self._stop_point_refs = stop_point_refs

    @property
    def status(self) -> V3Status:
        """Gets the status of this V3SiriReferenceDataMappingsResponse.


        :return: The status of this V3SiriReferenceDataMappingsResponse.
        :rtype: V3Status
        """
        return self._status

    @status.setter
    def status(self, status: V3Status):
        """Sets the status of this V3SiriReferenceDataMappingsResponse.


        :param status: The status of this V3SiriReferenceDataMappingsResponse.
        :type status: V3Status
        """

        self._status = status
