/*
 * PTV Timetable API - Version 3
 *
 * The PTV Timetable API provides direct access to Public Transport Victoria's public transport timetable data.    The API returns scheduled timetable, route and stop data for all metropolitan and regional train, tram and bus services in Victoria, including Night Network(Night Train and Night Tram data are included in metropolitan train and tram services data, respectively, whereas Night Bus is a separate route type).    The API also returns real-time data for metropolitan train, tram and bus services (where this data is made available to PTV), as well as disruption information, stop facility information, and access to myki ticket outlet data.    This Swagger is for Version 3 of the PTV Timetable API. By using this documentation you agree to comply with the licence and terms of service.    Train timetable data is updated daily, while the remaining data is updated weekly, taking into account any planned timetable changes (for example, due to holidays or planned disruptions). The PTV timetable API is the same API used by PTV for its apps. To access the most up to date data PTV has (including real-time data) you must use the API dynamically.    You can access the PTV Timetable API through a HTTP or HTTPS interface, as follows:        base URL / version number / API name / query string  The base URL is either:    *  http://timetableapi.ptv.vic.gov.au  or    *  https://timetableapi.ptv.vic.gov.au    The Swagger JSON file is available at http://timetableapi.ptv.vic.gov.au/swagger/docs/v3    Frequently asked questions are available on the PTV website at http://ptv.vic.gov.au/apifaq    Links to the following information are also provided on the PTV website at http://ptv.vic.gov.au/ptv-timetable-api/  * How to register for an API key and calculate a signature  * PTV Timetable API V2 to V3 Migration Guide  * PTV Timetable API Data Quality Statement    All information about how to use the API is in this documentation. PTV cannot provide technical support for the API.  
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class V3BulkDeparturesUpdateResponse : IEquatable<V3BulkDeparturesUpdateResponse>
    { 
        /// <summary>
        /// Timetabled and real-time service departures
        /// </summary>
        /// <value>Timetabled and real-time service departures</value>

        [DataMember(Name="departures")]
        public List<V3Departure> Departures { get; set; }

        /// <summary>
        /// Transport mode identifier
        /// </summary>
        /// <value>Transport mode identifier</value>

        [DataMember(Name="route_type")]
        public int? RouteType { get; set; }

        /// <summary>
        /// Stop identifier
        /// </summary>
        /// <value>Stop identifier</value>

        [DataMember(Name="stop_id")]
        public int? StopId { get; set; }

        /// <summary>
        /// Gets or Sets RequestedRouteDirection
        /// </summary>

        [DataMember(Name="requested_route_direction")]
        public V3BulkDeparturesRouteDirectionResponse RequestedRouteDirection { get; set; }

        /// <summary>
        /// The status of the route direction (changed | unchanged).  If changed, requests should change the requested_route_direction for the route_direction supplied.
        /// </summary>
        /// <value>The status of the route direction (changed | unchanged).  If changed, requests should change the requested_route_direction for the route_direction supplied.</value>
        
        public enum RouteDirectionStatusEnum
        {
            /// <summary>
            /// Enum NUMBER_0 for 0
            /// </summary>
            
            NUMBER_0 = 0,
            /// <summary>
            /// Enum NUMBER_1 for 1
            /// </summary>
            
            NUMBER_1 = 1        }

        /// <summary>
        /// The status of the route direction (changed | unchanged).  If changed, requests should change the requested_route_direction for the route_direction supplied.
        /// </summary>
        /// <value>The status of the route direction (changed | unchanged).  If changed, requests should change the requested_route_direction for the route_direction supplied.</value>

        [DataMember(Name="route_direction_status")]
        public RouteDirectionStatusEnum? RouteDirectionStatus { get; set; }

        /// <summary>
        /// Gets or Sets RouteDirection
        /// </summary>

        [DataMember(Name="route_direction")]
        public V3BulkDeparturesRouteDirectionResponse RouteDirection { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class V3BulkDeparturesUpdateResponse {\n");
            sb.Append("  Departures: ").Append(Departures).Append("\n");
            sb.Append("  RouteType: ").Append(RouteType).Append("\n");
            sb.Append("  StopId: ").Append(StopId).Append("\n");
            sb.Append("  RequestedRouteDirection: ").Append(RequestedRouteDirection).Append("\n");
            sb.Append("  RouteDirectionStatus: ").Append(RouteDirectionStatus).Append("\n");
            sb.Append("  RouteDirection: ").Append(RouteDirection).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((V3BulkDeparturesUpdateResponse)obj);
        }

        /// <summary>
        /// Returns true if V3BulkDeparturesUpdateResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of V3BulkDeparturesUpdateResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(V3BulkDeparturesUpdateResponse other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Departures == other.Departures ||
                    Departures != null &&
                    Departures.SequenceEqual(other.Departures)
                ) && 
                (
                    RouteType == other.RouteType ||
                    RouteType != null &&
                    RouteType.Equals(other.RouteType)
                ) && 
                (
                    StopId == other.StopId ||
                    StopId != null &&
                    StopId.Equals(other.StopId)
                ) && 
                (
                    RequestedRouteDirection == other.RequestedRouteDirection ||
                    RequestedRouteDirection != null &&
                    RequestedRouteDirection.Equals(other.RequestedRouteDirection)
                ) && 
                (
                    RouteDirectionStatus == other.RouteDirectionStatus ||
                    RouteDirectionStatus != null &&
                    RouteDirectionStatus.Equals(other.RouteDirectionStatus)
                ) && 
                (
                    RouteDirection == other.RouteDirection ||
                    RouteDirection != null &&
                    RouteDirection.Equals(other.RouteDirection)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Departures != null)
                    hashCode = hashCode * 59 + Departures.GetHashCode();
                    if (RouteType != null)
                    hashCode = hashCode * 59 + RouteType.GetHashCode();
                    if (StopId != null)
                    hashCode = hashCode * 59 + StopId.GetHashCode();
                    if (RequestedRouteDirection != null)
                    hashCode = hashCode * 59 + RequestedRouteDirection.GetHashCode();
                    if (RouteDirectionStatus != null)
                    hashCode = hashCode * 59 + RouteDirectionStatus.GetHashCode();
                    if (RouteDirection != null)
                    hashCode = hashCode * 59 + RouteDirection.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(V3BulkDeparturesUpdateResponse left, V3BulkDeparturesUpdateResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(V3BulkDeparturesUpdateResponse left, V3BulkDeparturesUpdateResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
