/* tslint:disable */
/* eslint-disable */
/**
 * PTV Timetable API - Version 3
 * The PTV Timetable API provides direct access to Public Transport Victoria\'s public transport timetable data.    The API returns scheduled timetable, route and stop data for all metropolitan and regional train, tram and bus services in Victoria, including Night Network(Night Train and Night Tram data are included in metropolitan train and tram services data, respectively, whereas Night Bus is a separate route type).    The API also returns real-time data for metropolitan train, tram and bus services (where this data is made available to PTV), as well as disruption information, stop facility information, and access to myki ticket outlet data.    This Swagger is for Version 3 of the PTV Timetable API. By using this documentation you agree to comply with the licence and terms of service.    Train timetable data is updated daily, while the remaining data is updated weekly, taking into account any planned timetable changes (for example, due to holidays or planned disruptions). The PTV timetable API is the same API used by PTV for its apps. To access the most up to date data PTV has (including real-time data) you must use the API dynamically.    You can access the PTV Timetable API through a HTTP or HTTPS interface, as follows:        base URL / version number / API name / query string  The base URL is either:    *  http://timetableapi.ptv.vic.gov.au  or    *  https://timetableapi.ptv.vic.gov.au    The Swagger JSON file is available at http://timetableapi.ptv.vic.gov.au/swagger/docs/v3    Frequently asked questions are available on the PTV website at http://ptv.vic.gov.au/apifaq    Links to the following information are also provided on the PTV website at http://ptv.vic.gov.au/ptv-timetable-api/  * How to register for an API key and calculate a signature  * PTV Timetable API V2 to V3 Migration Guide  * PTV Timetable API Data Quality Statement    All information about how to use the API is in this documentation. PTV cannot provide technical support for the API.  
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V3StopTicket
 */
export interface V3StopTicket {
    /**
     * Indicates the ticket type for the stop (myki, paper or both)
     * @type {string}
     * @memberof V3StopTicket
     */
    ticketType?: string;
    /**
     * Description of the zone
     * @type {string}
     * @memberof V3StopTicket
     */
    zone?: string;
    /**
     * Indicates whether the stop is inside the free fare zone
     * @type {boolean}
     * @memberof V3StopTicket
     */
    isFreeFareZone?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof V3StopTicket
     */
    ticketMachine?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof V3StopTicket
     */
    ticketChecks?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof V3StopTicket
     */
    vlineReservation?: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof V3StopTicket
     */
    ticketZones?: Array<number>;
}

/**
 * Check if a given object implements the V3StopTicket interface.
 */
export function instanceOfV3StopTicket(value: object): boolean {
    return true;
}

export function V3StopTicketFromJSON(json: any): V3StopTicket {
    return V3StopTicketFromJSONTyped(json, false);
}

export function V3StopTicketFromJSONTyped(json: any, ignoreDiscriminator: boolean): V3StopTicket {
    if (json == null) {
        return json;
    }
    return {
        
        'ticketType': json['ticket_type'] == null ? undefined : json['ticket_type'],
        'zone': json['zone'] == null ? undefined : json['zone'],
        'isFreeFareZone': json['is_free_fare_zone'] == null ? undefined : json['is_free_fare_zone'],
        'ticketMachine': json['ticket_machine'] == null ? undefined : json['ticket_machine'],
        'ticketChecks': json['ticket_checks'] == null ? undefined : json['ticket_checks'],
        'vlineReservation': json['vline_reservation'] == null ? undefined : json['vline_reservation'],
        'ticketZones': json['ticket_zones'] == null ? undefined : json['ticket_zones'],
    };
}

export function V3StopTicketToJSON(value?: V3StopTicket | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ticket_type': value['ticketType'],
        'zone': value['zone'],
        'is_free_fare_zone': value['isFreeFareZone'],
        'ticket_machine': value['ticketMachine'],
        'ticket_checks': value['ticketChecks'],
        'vline_reservation': value['vlineReservation'],
        'ticket_zones': value['ticketZones'],
    };
}

