/* tslint:disable */
/* eslint-disable */
/**
 * PTV Timetable API - Version 3
 * The PTV Timetable API provides direct access to Public Transport Victoria\'s public transport timetable data.    The API returns scheduled timetable, route and stop data for all metropolitan and regional train, tram and bus services in Victoria, including Night Network(Night Train and Night Tram data are included in metropolitan train and tram services data, respectively, whereas Night Bus is a separate route type).    The API also returns real-time data for metropolitan train, tram and bus services (where this data is made available to PTV), as well as disruption information, stop facility information, and access to myki ticket outlet data.    This Swagger is for Version 3 of the PTV Timetable API. By using this documentation you agree to comply with the licence and terms of service.    Train timetable data is updated daily, while the remaining data is updated weekly, taking into account any planned timetable changes (for example, due to holidays or planned disruptions). The PTV timetable API is the same API used by PTV for its apps. To access the most up to date data PTV has (including real-time data) you must use the API dynamically.    You can access the PTV Timetable API through a HTTP or HTTPS interface, as follows:        base URL / version number / API name / query string  The base URL is either:    *  http://timetableapi.ptv.vic.gov.au  or    *  https://timetableapi.ptv.vic.gov.au    The Swagger JSON file is available at http://timetableapi.ptv.vic.gov.au/swagger/docs/v3    Frequently asked questions are available on the PTV website at http://ptv.vic.gov.au/apifaq    Links to the following information are also provided on the PTV website at http://ptv.vic.gov.au/ptv-timetable-api/  * How to register for an API key and calculate a signature  * PTV Timetable API V2 to V3 Migration Guide  * PTV Timetable API Data Quality Statement    All information about how to use the API is in this documentation. PTV cannot provide technical support for the API.  
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V3StopAccessibilityWheelchair
 */
export interface V3StopAccessibilityWheelchair {
    /**
     * 
     * @type {boolean}
     * @memberof V3StopAccessibilityWheelchair
     */
    accessibleRamp?: boolean;
    /**
     * Indicates if there is at least one accessible parking spot at the stop that complies with the Disability Standards for Accessible Public Transport under the Disability Discrimination Act (1992)
     * @type {boolean}
     * @memberof V3StopAccessibilityWheelchair
     */
    parking?: boolean;
    /**
     * Indicates if there is at least one accessible telephone at the stop/platform that complies with the Disability Standards for Accessible Public Transport under the Disability Discrimination Act (1992)
     * @type {boolean}
     * @memberof V3StopAccessibilityWheelchair
     */
    telephone?: boolean;
    /**
     * Indicates if there is at least one accessible toilet at the stop/platform that complies with the Disability Standards for Accessible Public Transport under the Disability Discrimination Act (1992)
     * @type {boolean}
     * @memberof V3StopAccessibilityWheelchair
     */
    toilet?: boolean;
    /**
     * Indicates if there is at least one low ticket counter at the stop that complies with the Disability Standards for Accessible Public Transport under the Disability Discrimination Act (1992)
     * @type {boolean}
     * @memberof V3StopAccessibilityWheelchair
     */
    lowTicketCounter?: boolean;
    /**
     * Indicates if there is a space for mobility device to board on or off a transport mode
     * @type {boolean}
     * @memberof V3StopAccessibilityWheelchair
     */
    manouvering?: boolean;
    /**
     * Indicates if there is a raised platform to board a train
     * @type {boolean}
     * @memberof V3StopAccessibilityWheelchair
     */
    raisedPlatform?: boolean;
    /**
     * Indicates if there are ramps (&lt;1:14) at the stop/platform
     * @type {boolean}
     * @memberof V3StopAccessibilityWheelchair
     */
    ramp?: boolean;
    /**
     * Indicates if there is a path beyond the stop which is accessible
     * @type {boolean}
     * @memberof V3StopAccessibilityWheelchair
     */
    secondaryPath?: boolean;
    /**
     * Indicates if there is shelter near the raised platform
     * @type {boolean}
     * @memberof V3StopAccessibilityWheelchair
     */
    raisedPlatformShelther?: boolean;
    /**
     * Indicates if there are ramps (&gt;1:14) at the stop/platform
     * @type {boolean}
     * @memberof V3StopAccessibilityWheelchair
     */
    steepRamp?: boolean;
}

/**
 * Check if a given object implements the V3StopAccessibilityWheelchair interface.
 */
export function instanceOfV3StopAccessibilityWheelchair(value: object): boolean {
    return true;
}

export function V3StopAccessibilityWheelchairFromJSON(json: any): V3StopAccessibilityWheelchair {
    return V3StopAccessibilityWheelchairFromJSONTyped(json, false);
}

export function V3StopAccessibilityWheelchairFromJSONTyped(json: any, ignoreDiscriminator: boolean): V3StopAccessibilityWheelchair {
    if (json == null) {
        return json;
    }
    return {
        
        'accessibleRamp': json['accessible_ramp'] == null ? undefined : json['accessible_ramp'],
        'parking': json['parking'] == null ? undefined : json['parking'],
        'telephone': json['telephone'] == null ? undefined : json['telephone'],
        'toilet': json['toilet'] == null ? undefined : json['toilet'],
        'lowTicketCounter': json['low_ticket_counter'] == null ? undefined : json['low_ticket_counter'],
        'manouvering': json['manouvering'] == null ? undefined : json['manouvering'],
        'raisedPlatform': json['raised_platform'] == null ? undefined : json['raised_platform'],
        'ramp': json['ramp'] == null ? undefined : json['ramp'],
        'secondaryPath': json['secondary_path'] == null ? undefined : json['secondary_path'],
        'raisedPlatformShelther': json['raised_platform_shelther'] == null ? undefined : json['raised_platform_shelther'],
        'steepRamp': json['steep_ramp'] == null ? undefined : json['steep_ramp'],
    };
}

export function V3StopAccessibilityWheelchairToJSON(value?: V3StopAccessibilityWheelchair | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'accessible_ramp': value['accessibleRamp'],
        'parking': value['parking'],
        'telephone': value['telephone'],
        'toilet': value['toilet'],
        'low_ticket_counter': value['lowTicketCounter'],
        'manouvering': value['manouvering'],
        'raised_platform': value['raisedPlatform'],
        'ramp': value['ramp'],
        'secondary_path': value['secondaryPath'],
        'raised_platform_shelther': value['raisedPlatformShelther'],
        'steep_ramp': value['steepRamp'],
    };
}

