using System;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Model {

  /// <summary>
  /// 
  /// </summary>
  [DataContract]
  public class V3SiriReferenceDataRequest {
    /// <summary>
    /// Gets or Sets LineRefs
    /// </summary>
    [DataMember(Name="line_refs", EmitDefaultValue=false)]
    [JsonProperty(PropertyName = "line_refs")]
    public List<V3SiriLineRefDirectionRefStopPointRef> LineRefs { get; set; }

    /// <summary>
    /// Siri StopPointRef
    /// </summary>
    /// <value>Siri StopPointRef</value>
    [DataMember(Name="stop_point_refs", EmitDefaultValue=false)]
    [JsonProperty(PropertyName = "stop_point_refs")]
    public List<int?> StopPointRefs { get; set; }

    /// <summary>
    /// Filter by the date and time of the request (ISO 8601 UTC format) (default = current date and time)
    /// </summary>
    /// <value>Filter by the date and time of the request (ISO 8601 UTC format) (default = current date and time)</value>
    [DataMember(Name="date_utc", EmitDefaultValue=false)]
    [JsonProperty(PropertyName = "date_utc")]
    public DateTime? DateUtc { get; set; }

    /// <summary>
    /// DIVA mapping version generated by Chronos during a Parser or RealtimeBusConfig load
    /// </summary>
    /// <value>DIVA mapping version generated by Chronos during a Parser or RealtimeBusConfig load</value>
    [DataMember(Name="mapping_version", EmitDefaultValue=false)]
    [JsonProperty(PropertyName = "mapping_version")]
    public string MappingVersion { get; set; }


    /// <summary>
    /// Get the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()  {
      var sb = new StringBuilder();
      sb.Append("class V3SiriReferenceDataRequest {\n");
      sb.Append("  LineRefs: ").Append(LineRefs).Append("\n");
      sb.Append("  StopPointRefs: ").Append(StopPointRefs).Append("\n");
      sb.Append("  DateUtc: ").Append(DateUtc).Append("\n");
      sb.Append("  MappingVersion: ").Append(MappingVersion).Append("\n");
      sb.Append("}\n");
      return sb.ToString();
    }

    /// <summary>
    /// Get the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public string ToJson() {
      return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

}
}
