/**
* PTV Timetable API - Version 3
* The PTV Timetable API provides direct access to Public Transport Victoria's public transport timetable data.    The API returns scheduled timetable, route and stop data for all metropolitan and regional train, tram and bus services in Victoria, including Night Network(Night Train and Night Tram data are included in metropolitan train and tram services data, respectively, whereas Night Bus is a separate route type).    The API also returns real-time data for metropolitan train, tram and bus services (where this data is made available to PTV), as well as disruption information, stop facility information, and access to myki ticket outlet data.    This Swagger is for Version 3 of the PTV Timetable API. By using this documentation you agree to comply with the licence and terms of service.    Train timetable data is updated daily, while the remaining data is updated weekly, taking into account any planned timetable changes (for example, due to holidays or planned disruptions). The PTV timetable API is the same API used by PTV for its apps. To access the most up to date data PTV has (including real-time data) you must use the API dynamically.    You can access the PTV Timetable API through a HTTP or HTTPS interface, as follows:        base URL / version number / API name / query string  The base URL is either:    *  http://timetableapi.ptv.vic.gov.au  or    *  https://timetableapi.ptv.vic.gov.au    The Swagger JSON file is available at http://timetableapi.ptv.vic.gov.au/swagger/docs/v3    Frequently asked questions are available on the PTV website at http://ptv.vic.gov.au/apifaq    Links to the following information are also provided on the PTV website at http://ptv.vic.gov.au/ptv-timetable-api/  * How to register for an API key and calculate a signature  * PTV Timetable API V2 to V3 Migration Guide  * PTV Timetable API Data Quality Statement    All information about how to use the API is in this documentation. PTV cannot provide technical support for the API.  
*
* OpenAPI spec version: v3
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/package io.swagger.server.apis

import com.google.gson.Gson
import io.ktor.application.call
import io.ktor.auth.UserIdPrincipal
import io.ktor.auth.authentication
import io.ktor.auth.authenticate
import io.ktor.auth.OAuthAccessTokenResponse
import io.ktor.auth.OAuthServerSettings
import io.ktor.http.ContentType
import io.ktor.http.HttpStatusCode
import io.ktor.locations.KtorExperimentalLocationsAPI
import io.ktor.locations.delete
import io.ktor.locations.get
import io.ktor.locations.post
import io.ktor.locations.put
import io.ktor.locations.patch
import io.ktor.response.respond
import io.ktor.response.respondText
import io.ktor.routing.Route
import io.ktor.routing.route

import io.swagger.server.Paths
import io.swagger.server.infrastructure.ApiPrincipal


import io.swagger.server.models.V3ErrorResponse
import io.swagger.server.models.V3SearchResult

@KtorExperimentalLocationsAPI
fun Route.SearchApi() {
    val gson = Gson()
    val empty = mutableMapOf<String, Any?>()
    get<Paths.searchSearch> {  _: Paths.searchSearch ->
        val exampleContentType = "application/json"
        val exampleContentString = """{
  "routes" : [ null, null ],
  "outlets" : [ {
    "outlet_business_hour_thur" : "outlet_business_hour_thur",
    "outlet_postcode" : 7,
    "outlet_business_hour_fri" : "outlet_business_hour_fri",
    "outlet_business_hour_wed" : "outlet_business_hour_wed",
    "outlet_suburb" : "outlet_suburb",
    "outlet_longitude" : 4.145608,
    "outlet_name" : "outlet_name",
    "outlet_distance" : 3.6160767,
    "outlet_business" : "outlet_business",
    "outlet_business_hour_mon" : "outlet_business_hour_mon",
    "outlet_business_hour_sun" : "outlet_business_hour_sun",
    "outlet_slid_spid" : "outlet_slid_spid",
    "outlet_business_hour_sat" : "outlet_business_hour_sat",
    "outlet_notes" : "outlet_notes",
    "outlet_business_hour_tue" : "outlet_business_hour_tue",
    "outlet_latitude" : 2.027123
  }, {
    "outlet_business_hour_thur" : "outlet_business_hour_thur",
    "outlet_postcode" : 7,
    "outlet_business_hour_fri" : "outlet_business_hour_fri",
    "outlet_business_hour_wed" : "outlet_business_hour_wed",
    "outlet_suburb" : "outlet_suburb",
    "outlet_longitude" : 4.145608,
    "outlet_name" : "outlet_name",
    "outlet_distance" : 3.6160767,
    "outlet_business" : "outlet_business",
    "outlet_business_hour_mon" : "outlet_business_hour_mon",
    "outlet_business_hour_sun" : "outlet_business_hour_sun",
    "outlet_slid_spid" : "outlet_slid_spid",
    "outlet_business_hour_sat" : "outlet_business_hour_sat",
    "outlet_notes" : "outlet_notes",
    "outlet_business_hour_tue" : "outlet_business_hour_tue",
    "outlet_latitude" : 2.027123
  } ],
  "stops" : [ {
    "routes" : [ {
      "route_service_status" : {
        "description" : "description",
        "timestamp" : "2000-01-23T04:56:07.000+00:00"
      },
      "route_id" : 5,
      "route_name" : "route_name",
      "route_type" : 1,
      "route_number" : "route_number",
      "route_gtfs_id" : "route_gtfs_id"
    }, {
      "route_service_status" : {
        "description" : "description",
        "timestamp" : "2000-01-23T04:56:07.000+00:00"
      },
      "route_id" : 5,
      "route_name" : "route_name",
      "route_type" : 1,
      "route_number" : "route_number",
      "route_gtfs_id" : "route_gtfs_id"
    } ],
    "stop_longitude" : 2.302136,
    "stop_sequence" : 7,
    "route_type" : 6,
    "stop_id" : 9,
    "stop_landmark" : "stop_landmark",
    "stop_suburb" : "stop_suburb",
    "stop_distance" : 0.8008282,
    "stop_name" : "stop_name",
    "stop_latitude" : 5.637377
  }, {
    "routes" : [ {
      "route_service_status" : {
        "description" : "description",
        "timestamp" : "2000-01-23T04:56:07.000+00:00"
      },
      "route_id" : 5,
      "route_name" : "route_name",
      "route_type" : 1,
      "route_number" : "route_number",
      "route_gtfs_id" : "route_gtfs_id"
    }, {
      "route_service_status" : {
        "description" : "description",
        "timestamp" : "2000-01-23T04:56:07.000+00:00"
      },
      "route_id" : 5,
      "route_name" : "route_name",
      "route_type" : 1,
      "route_number" : "route_number",
      "route_gtfs_id" : "route_gtfs_id"
    } ],
    "stop_longitude" : 2.302136,
    "stop_sequence" : 7,
    "route_type" : 6,
    "stop_id" : 9,
    "stop_landmark" : "stop_landmark",
    "stop_suburb" : "stop_suburb",
    "stop_distance" : 0.8008282,
    "stop_name" : "stop_name",
    "stop_latitude" : 5.637377
  } ],
  "status" : {
    "health" : 6,
    "version" : "version"
  }
}"""
        
        when(exampleContentType) {
            "application/json" -> call.respond(gson.fromJson(exampleContentString, empty::class.java))
            "application/xml" -> call.respondText(exampleContentString, ContentType.Text.Xml)
            else -> call.respondText(exampleContentString)
        }    }
}
