//
// V3SiriDownstreamSubscriptionDeleteRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V3SiriDownstreamSubscriptionDeleteRequest: Codable {

    /** Siri Subscriber Ref */
    public var subscriberRef: String
    /** Siri Subscription Reference(s) - Unique to a Subscriber Ref.  If &#x60;null&#x60;, then all subscriptions will be terminated for the referenced Subscriber. */
    public var subscriptionRef: [String]?

    public init(subscriberRef: String, subscriptionRef: [String]? = nil) {
        self.subscriberRef = subscriberRef
        self.subscriptionRef = subscriptionRef
    }

    public enum CodingKeys: String, CodingKey { 
        case subscriberRef = "subscriber_ref"
        case subscriptionRef = "subscription_ref"
    }

}
