//
// V3StoppingPattern.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V3StoppingPattern: Codable {

    /** Disruption information applicable to relevant routes or stops */
    public var disruptions: [V3Disruption]?
    /** Timetabled and real-time service departures */
    public var departures: [V3PatternDeparture]?
    /** A train station, tram stop, bus stop, regional coach stop or Night Bus stop */
    public var stops: [String:V3StoppingPatternStop]?
    /** Train lines, tram routes, bus routes, regional coach routes, Night Bus routes */
    public var routes: [String:Any]?
    /** Individual trips/services of a route */
    public var runs: [String:V3Run]?
    /** Directions of travel of route */
    public var directions: [String:V3Direction]?
    public var status: V3Status?

    public init(disruptions: [V3Disruption]? = nil, departures: [V3PatternDeparture]? = nil, stops: [String:V3StoppingPatternStop]? = nil, routes: [String:Any]? = nil, runs: [String:V3Run]? = nil, directions: [String:V3Direction]? = nil, status: V3Status? = nil) {
        self.disruptions = disruptions
        self.departures = departures
        self.stops = stops
        self.routes = routes
        self.runs = runs
        self.directions = directions
        self.status = status
    }


}
