/**
* PTV Timetable API - Version 3
* The PTV Timetable API provides direct access to Public Transport Victoria's public transport timetable data.    The API returns scheduled timetable, route and stop data for all metropolitan and regional train, tram and bus services in Victoria, including Night Network(Night Train and Night Tram data are included in metropolitan train and tram services data, respectively, whereas Night Bus is a separate route type).    The API also returns real-time data for metropolitan train, tram and bus services (where this data is made available to PTV), as well as disruption information, stop facility information, and access to myki ticket outlet data.    This Swagger is for Version 3 of the PTV Timetable API. By using this documentation you agree to comply with the licence and terms of service.    Train timetable data is updated daily, while the remaining data is updated weekly, taking into account any planned timetable changes (for example, due to holidays or planned disruptions). The PTV timetable API is the same API used by PTV for its apps. To access the most up to date data PTV has (including real-time data) you must use the API dynamically.    You can access the PTV Timetable API through a HTTP or HTTPS interface, as follows:        base URL / version number / API name / query string  The base URL is either:    *  http://timetableapi.ptv.vic.gov.au  or    *  https://timetableapi.ptv.vic.gov.au    The Swagger JSON file is available at http://timetableapi.ptv.vic.gov.au/swagger/docs/v3    Frequently asked questions are available on the PTV website at http://ptv.vic.gov.au/apifaq    Links to the following information are also provided on the PTV website at http://ptv.vic.gov.au/ptv-timetable-api/  * How to register for an API key and calculate a signature  * PTV Timetable API V2 to V3 Migration Guide  * PTV Timetable API Data Quality Statement    All information about how to use the API is in this documentation. PTV cannot provide technical support for the API.  
*
* OpenAPI spec version: v3
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/package io.swagger.server.models

import io.swagger.server.models.V3DisruptionRoute
import io.swagger.server.models.V3DisruptionStop

/**
 * 
 * @param disruptionId Disruption information identifier
 * @param title Headline title summarising disruption information
 * @param url URL of relevant article on PTV website
 * @param description Description of the disruption
 * @param disruptionStatus Status of the disruption (e.g. \"Planned\", \"Current\")
 * @param disruptionType Type of disruption
 * @param publishedOn Date and time disruption information is published on PTV website, in ISO 8601 UTC format
 * @param lastUpdated Date and time disruption information was last updated by PTV, in ISO 8601 UTC format
 * @param fromDate Date and time at which disruption begins, in ISO 8601 UTC format
 * @param toDate Date and time at which disruption ends, in ISO 8601 UTC format (returns null if unknown)
 * @param routes Route relevant to a disruption (if applicable)
 * @param stops Stop relevant to a disruption (if applicable)
 * @param colour 
 * @param displayOnBoard 
 * @param displayStatus 
 */
data class V3Disruption (

    /* Disruption information identifier */
    val disruptionId: kotlin.Long? = null,
    /* Headline title summarising disruption information */
    val title: kotlin.String? = null,
    /* URL of relevant article on PTV website */
    val url: kotlin.String? = null,
    /* Description of the disruption */
    val description: kotlin.String? = null,
    /* Status of the disruption (e.g. \"Planned\", \"Current\") */
    val disruptionStatus: kotlin.String? = null,
    /* Type of disruption */
    val disruptionType: kotlin.String? = null,
    /* Date and time disruption information is published on PTV website, in ISO 8601 UTC format */
    val publishedOn: java.time.LocalDateTime? = null,
    /* Date and time disruption information was last updated by PTV, in ISO 8601 UTC format */
    val lastUpdated: java.time.LocalDateTime? = null,
    /* Date and time at which disruption begins, in ISO 8601 UTC format */
    val fromDate: java.time.LocalDateTime? = null,
    /* Date and time at which disruption ends, in ISO 8601 UTC format (returns null if unknown) */
    val toDate: java.time.LocalDateTime? = null,
    /* Route relevant to a disruption (if applicable) */
    val routes: kotlin.Array<V3DisruptionRoute>? = null,
    /* Stop relevant to a disruption (if applicable) */
    val stops: kotlin.Array<V3DisruptionStop>? = null,
    val colour: kotlin.String? = null,
    val displayOnBoard: kotlin.Boolean? = null,
    val displayStatus: kotlin.Boolean? = null
) {
}
