/* tslint:disable */
/* eslint-disable */
/**
 * PTV Timetable API - Version 3
 * The PTV Timetable API provides direct access to Public Transport Victoria\'s public transport timetable data.    The API returns scheduled timetable, route and stop data for all metropolitan and regional train, tram and bus services in Victoria, including Night Network(Night Train and Night Tram data are included in metropolitan train and tram services data, respectively, whereas Night Bus is a separate route type).    The API also returns real-time data for metropolitan train, tram and bus services (where this data is made available to PTV), as well as disruption information, stop facility information, and access to myki ticket outlet data.    This Swagger is for Version 3 of the PTV Timetable API. By using this documentation you agree to comply with the licence and terms of service.    Train timetable data is updated daily, while the remaining data is updated weekly, taking into account any planned timetable changes (for example, due to holidays or planned disruptions). The PTV timetable API is the same API used by PTV for its apps. To access the most up to date data PTV has (including real-time data) you must use the API dynamically.    You can access the PTV Timetable API through a HTTP or HTTPS interface, as follows:        base URL / version number / API name / query string  The base URL is either:    *  http://timetableapi.ptv.vic.gov.au  or    *  https://timetableapi.ptv.vic.gov.au    The Swagger JSON file is available at http://timetableapi.ptv.vic.gov.au/swagger/docs/v3    Frequently asked questions are available on the PTV website at http://ptv.vic.gov.au/apifaq    Links to the following information are also provided on the PTV website at http://ptv.vic.gov.au/ptv-timetable-api/  * How to register for an API key and calculate a signature  * PTV Timetable API V2 to V3 Migration Guide  * PTV Timetable API Data Quality Statement    All information about how to use the API is in this documentation. PTV cannot provide technical support for the API.  
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V3DeparturesBroadParameters
 */
export interface V3DeparturesBroadParameters {
    /**
     * Filter by platform number at stop
     * @type {Array<number>}
     * @memberof V3DeparturesBroadParameters
     */
    platformNumbers?: Array<number>;
    /**
     * Filter by identifier of direction of travel; values returned by Directions API - /v3/directions/route/{route_id}
     * @type {number}
     * @memberof V3DeparturesBroadParameters
     */
    directionId?: number;
    /**
     * Indicates that stop_id parameter will accept "GTFS stop_id" data
     * @type {boolean}
     * @memberof V3DeparturesBroadParameters
     */
    gtfs?: boolean;
    /**
     * Filter by the date and time of the request (ISO 8601 UTC format) (default = current date and time)
     * @type {Date}
     * @memberof V3DeparturesBroadParameters
     */
    dateUtc?: Date;
    /**
     * Maximum number of results returned
     * @type {number}
     * @memberof V3DeparturesBroadParameters
     */
    maxResults?: number;
    /**
     * Indicates if cancelled services (if they exist) are returned (default = false) - metropolitan train only
     * @type {boolean}
     * @memberof V3DeparturesBroadParameters
     */
    includeCancelled?: boolean;
    /**
     * Indicates if filtering runs (and their departures) to those that arrive at destination before date_utc (default = false). Requires max_results &gt; 0.
     * @type {boolean}
     * @memberof V3DeparturesBroadParameters
     */
    lookBackwards?: boolean;
    /**
     * List of objects to be returned in full (i.e. expanded) - options include: All, Stop, Route, Run, Direction, Disruption, VehiclePosition, VehicleDescriptor or None.
     * Run must be expanded to receive VehiclePosition and VehicleDescriptor information.
     * @type {Array<string>}
     * @memberof V3DeparturesBroadParameters
     */
    expand?: Array<V3DeparturesBroadParametersExpandEnum>;
    /**
     * Indicates if the route geopath should be returned
     * @type {boolean}
     * @memberof V3DeparturesBroadParameters
     */
    includeGeopath?: boolean;
}


/**
 * @export
 */
export const V3DeparturesBroadParametersExpandEnum = {
    All: 'All',
    Stop: 'Stop',
    Route: 'Route',
    Run: 'Run',
    Direction: 'Direction',
    Disruption: 'Disruption',
    VehicleDescriptor: 'VehicleDescriptor',
    VehiclePosition: 'VehiclePosition',
    None: 'None'
} as const;
export type V3DeparturesBroadParametersExpandEnum = typeof V3DeparturesBroadParametersExpandEnum[keyof typeof V3DeparturesBroadParametersExpandEnum];


/**
 * Check if a given object implements the V3DeparturesBroadParameters interface.
 */
export function instanceOfV3DeparturesBroadParameters(value: object): boolean {
    return true;
}

export function V3DeparturesBroadParametersFromJSON(json: any): V3DeparturesBroadParameters {
    return V3DeparturesBroadParametersFromJSONTyped(json, false);
}

export function V3DeparturesBroadParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): V3DeparturesBroadParameters {
    if (json == null) {
        return json;
    }
    return {
        
        'platformNumbers': json['platform_numbers'] == null ? undefined : json['platform_numbers'],
        'directionId': json['direction_id'] == null ? undefined : json['direction_id'],
        'gtfs': json['gtfs'] == null ? undefined : json['gtfs'],
        'dateUtc': json['date_utc'] == null ? undefined : (new Date(json['date_utc'])),
        'maxResults': json['max_results'] == null ? undefined : json['max_results'],
        'includeCancelled': json['include_cancelled'] == null ? undefined : json['include_cancelled'],
        'lookBackwards': json['look_backwards'] == null ? undefined : json['look_backwards'],
        'expand': json['expand'] == null ? undefined : json['expand'],
        'includeGeopath': json['include_geopath'] == null ? undefined : json['include_geopath'],
    };
}

export function V3DeparturesBroadParametersToJSON(value?: V3DeparturesBroadParameters | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'platform_numbers': value['platformNumbers'],
        'direction_id': value['directionId'],
        'gtfs': value['gtfs'],
        'date_utc': value['dateUtc'] == null ? undefined : ((value['dateUtc']).toISOString()),
        'max_results': value['maxResults'],
        'include_cancelled': value['includeCancelled'],
        'look_backwards': value['lookBackwards'],
        'expand': value['expand'],
        'include_geopath': value['includeGeopath'],
    };
}

