/*
 * PTV Timetable API - Version 3
 * The PTV Timetable API provides direct access to Public Transport Victoria's public transport timetable data.    The API returns scheduled timetable, route and stop data for all metropolitan and regional train, tram and bus services in Victoria, including Night Network(Night Train and Night Tram data are included in metropolitan train and tram services data, respectively, whereas Night Bus is a separate route type).    The API also returns real-time data for metropolitan train, tram and bus services (where this data is made available to PTV), as well as disruption information, stop facility information, and access to myki ticket outlet data.    This Swagger is for Version 3 of the PTV Timetable API. By using this documentation you agree to comply with the licence and terms of service.    Train timetable data is updated daily, while the remaining data is updated weekly, taking into account any planned timetable changes (for example, due to holidays or planned disruptions). The PTV timetable API is the same API used by PTV for its apps. To access the most up to date data PTV has (including real-time data) you must use the API dynamically.    You can access the PTV Timetable API through a HTTP or HTTPS interface, as follows:        base URL / version number / API name / query string  The base URL is either:    *  http://timetableapi.ptv.vic.gov.au  or    *  https://timetableapi.ptv.vic.gov.au    The Swagger JSON file is available at http://timetableapi.ptv.vic.gov.au/swagger/docs/v3    Frequently asked questions are available on the PTV website at http://ptv.vic.gov.au/apifaq    Links to the following information are also provided on the PTV website at http://ptv.vic.gov.au/ptv-timetable-api/  * How to register for an API key and calculate a signature  * PTV Timetable API V2 to V3 Migration Guide  * PTV Timetable API Data Quality Statement    All information about how to use the API is in this documentation. PTV cannot provide technical support for the API.  
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for V3StopStaffing
 */
public class V3StopStaffingTest {
    private final V3StopStaffing model = new V3StopStaffing();

    /**
     * Model tests for V3StopStaffing
     */
    @Test
    public void testV3StopStaffing() {
        // TODO: test V3StopStaffing
    }

    /**
     * Test the property 'friAmFrom'
     */
    @Test
    public void friAmFromTest() {
        // TODO: test friAmFrom
    }

    /**
     * Test the property 'friAmTo'
     */
    @Test
    public void friAmToTest() {
        // TODO: test friAmTo
    }

    /**
     * Test the property 'friPmFrom'
     */
    @Test
    public void friPmFromTest() {
        // TODO: test friPmFrom
    }

    /**
     * Test the property 'friPmTo'
     */
    @Test
    public void friPmToTest() {
        // TODO: test friPmTo
    }

    /**
     * Test the property 'monAmFrom'
     */
    @Test
    public void monAmFromTest() {
        // TODO: test monAmFrom
    }

    /**
     * Test the property 'monAmTo'
     */
    @Test
    public void monAmToTest() {
        // TODO: test monAmTo
    }

    /**
     * Test the property 'monPmFrom'
     */
    @Test
    public void monPmFromTest() {
        // TODO: test monPmFrom
    }

    /**
     * Test the property 'monPmTo'
     */
    @Test
    public void monPmToTest() {
        // TODO: test monPmTo
    }

    /**
     * Test the property 'phAdditionalText'
     */
    @Test
    public void phAdditionalTextTest() {
        // TODO: test phAdditionalText
    }

    /**
     * Test the property 'phFrom'
     */
    @Test
    public void phFromTest() {
        // TODO: test phFrom
    }

    /**
     * Test the property 'phTo'
     */
    @Test
    public void phToTest() {
        // TODO: test phTo
    }

    /**
     * Test the property 'satAmFrom'
     */
    @Test
    public void satAmFromTest() {
        // TODO: test satAmFrom
    }

    /**
     * Test the property 'satAmTo'
     */
    @Test
    public void satAmToTest() {
        // TODO: test satAmTo
    }

    /**
     * Test the property 'satPmFrom'
     */
    @Test
    public void satPmFromTest() {
        // TODO: test satPmFrom
    }

    /**
     * Test the property 'satPmTo'
     */
    @Test
    public void satPmToTest() {
        // TODO: test satPmTo
    }

    /**
     * Test the property 'sunAmFrom'
     */
    @Test
    public void sunAmFromTest() {
        // TODO: test sunAmFrom
    }

    /**
     * Test the property 'sunAmTo'
     */
    @Test
    public void sunAmToTest() {
        // TODO: test sunAmTo
    }

    /**
     * Test the property 'sunPmFrom'
     */
    @Test
    public void sunPmFromTest() {
        // TODO: test sunPmFrom
    }

    /**
     * Test the property 'sunPmTo'
     */
    @Test
    public void sunPmToTest() {
        // TODO: test sunPmTo
    }

    /**
     * Test the property 'thuAmFrom'
     */
    @Test
    public void thuAmFromTest() {
        // TODO: test thuAmFrom
    }

    /**
     * Test the property 'thuAmTo'
     */
    @Test
    public void thuAmToTest() {
        // TODO: test thuAmTo
    }

    /**
     * Test the property 'thuPmFrom'
     */
    @Test
    public void thuPmFromTest() {
        // TODO: test thuPmFrom
    }

    /**
     * Test the property 'thuPmTo'
     */
    @Test
    public void thuPmToTest() {
        // TODO: test thuPmTo
    }

    /**
     * Test the property 'tueAmFrom'
     */
    @Test
    public void tueAmFromTest() {
        // TODO: test tueAmFrom
    }

    /**
     * Test the property 'tueAmTo'
     */
    @Test
    public void tueAmToTest() {
        // TODO: test tueAmTo
    }

    /**
     * Test the property 'tuePmFrom'
     */
    @Test
    public void tuePmFromTest() {
        // TODO: test tuePmFrom
    }

    /**
     * Test the property 'tuePmTo'
     */
    @Test
    public void tuePmToTest() {
        // TODO: test tuePmTo
    }

    /**
     * Test the property 'wedAmFrom'
     */
    @Test
    public void wedAmFromTest() {
        // TODO: test wedAmFrom
    }

    /**
     * Test the property 'wedAmTo'
     */
    @Test
    public void wedAmToTest() {
        // TODO: test wedAmTo
    }

    /**
     * Test the property 'wedPmFrom'
     */
    @Test
    public void wedPmFromTest() {
        // TODO: test wedPmFrom
    }

    /**
     * Test the property 'wedPmTo'
     */
    @Test
    public void wedPmToTest() {
        // TODO: test wedPmTo
    }

}
