/* 
 * PTV Timetable API - Version 3
 *
 * The PTV Timetable API provides direct access to Public Transport Victoria's public transport timetable data.    The API returns scheduled timetable, route and stop data for all metropolitan and regional train, tram and bus services in Victoria, including Night Network(Night Train and Night Tram data are included in metropolitan train and tram services data, respectively, whereas Night Bus is a separate route type).    The API also returns real-time data for metropolitan train, tram and bus services (where this data is made available to PTV), as well as disruption information, stop facility information, and access to myki ticket outlet data.    This Swagger is for Version 3 of the PTV Timetable API. By using this documentation you agree to comply with the licence and terms of service.    Train timetable data is updated daily, while the remaining data is updated weekly, taking into account any planned timetable changes (for example, due to holidays or planned disruptions). The PTV timetable API is the same API used by PTV for its apps. To access the most up to date data PTV has (including real-time data) you must use the API dynamically.    You can access the PTV Timetable API through a HTTP or HTTPS interface, as follows:        base URL / version number / API name / query string  The base URL is either:    *  http://timetableapi.ptv.vic.gov.au  or    *  https://timetableapi.ptv.vic.gov.au    The Swagger JSON file is available at http://timetableapi.ptv.vic.gov.au/swagger/docs/v3    Frequently asked questions are available on the PTV website at http://ptv.vic.gov.au/apifaq    Links to the following information are also provided on the PTV website at http://ptv.vic.gov.au/ptv-timetable-api/  * How to register for an API key and calculate a signature  * PTV Timetable API V2 to V3 Migration Guide  * PTV Timetable API Data Quality Statement    All information about how to use the API is in this documentation. PTV cannot provide technical support for the API.  
 *
 * OpenAPI spec version: v3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing V3StopStaffing
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V3StopStaffingTests
    {
        // TODO uncomment below to declare an instance variable for V3StopStaffing
        //private V3StopStaffing instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V3StopStaffing
            //instance = new V3StopStaffing();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V3StopStaffing
        /// </summary>
        [Test]
        public void V3StopStaffingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V3StopStaffing
            //Assert.IsInstanceOfType<V3StopStaffing> (instance, "variable 'instance' is a V3StopStaffing");
        }


        /// <summary>
        /// Test the property 'FriAmFrom'
        /// </summary>
        [Test]
        public void FriAmFromTest()
        {
            // TODO unit test for the property 'FriAmFrom'
        }
        /// <summary>
        /// Test the property 'FriAmTo'
        /// </summary>
        [Test]
        public void FriAmToTest()
        {
            // TODO unit test for the property 'FriAmTo'
        }
        /// <summary>
        /// Test the property 'FriPmFrom'
        /// </summary>
        [Test]
        public void FriPmFromTest()
        {
            // TODO unit test for the property 'FriPmFrom'
        }
        /// <summary>
        /// Test the property 'FriPmTo'
        /// </summary>
        [Test]
        public void FriPmToTest()
        {
            // TODO unit test for the property 'FriPmTo'
        }
        /// <summary>
        /// Test the property 'MonAmFrom'
        /// </summary>
        [Test]
        public void MonAmFromTest()
        {
            // TODO unit test for the property 'MonAmFrom'
        }
        /// <summary>
        /// Test the property 'MonAmTo'
        /// </summary>
        [Test]
        public void MonAmToTest()
        {
            // TODO unit test for the property 'MonAmTo'
        }
        /// <summary>
        /// Test the property 'MonPmFrom'
        /// </summary>
        [Test]
        public void MonPmFromTest()
        {
            // TODO unit test for the property 'MonPmFrom'
        }
        /// <summary>
        /// Test the property 'MonPmTo'
        /// </summary>
        [Test]
        public void MonPmToTest()
        {
            // TODO unit test for the property 'MonPmTo'
        }
        /// <summary>
        /// Test the property 'PhAdditionalText'
        /// </summary>
        [Test]
        public void PhAdditionalTextTest()
        {
            // TODO unit test for the property 'PhAdditionalText'
        }
        /// <summary>
        /// Test the property 'PhFrom'
        /// </summary>
        [Test]
        public void PhFromTest()
        {
            // TODO unit test for the property 'PhFrom'
        }
        /// <summary>
        /// Test the property 'PhTo'
        /// </summary>
        [Test]
        public void PhToTest()
        {
            // TODO unit test for the property 'PhTo'
        }
        /// <summary>
        /// Test the property 'SatAmFrom'
        /// </summary>
        [Test]
        public void SatAmFromTest()
        {
            // TODO unit test for the property 'SatAmFrom'
        }
        /// <summary>
        /// Test the property 'SatAmTo'
        /// </summary>
        [Test]
        public void SatAmToTest()
        {
            // TODO unit test for the property 'SatAmTo'
        }
        /// <summary>
        /// Test the property 'SatPmFrom'
        /// </summary>
        [Test]
        public void SatPmFromTest()
        {
            // TODO unit test for the property 'SatPmFrom'
        }
        /// <summary>
        /// Test the property 'SatPmTo'
        /// </summary>
        [Test]
        public void SatPmToTest()
        {
            // TODO unit test for the property 'SatPmTo'
        }
        /// <summary>
        /// Test the property 'SunAmFrom'
        /// </summary>
        [Test]
        public void SunAmFromTest()
        {
            // TODO unit test for the property 'SunAmFrom'
        }
        /// <summary>
        /// Test the property 'SunAmTo'
        /// </summary>
        [Test]
        public void SunAmToTest()
        {
            // TODO unit test for the property 'SunAmTo'
        }
        /// <summary>
        /// Test the property 'SunPmFrom'
        /// </summary>
        [Test]
        public void SunPmFromTest()
        {
            // TODO unit test for the property 'SunPmFrom'
        }
        /// <summary>
        /// Test the property 'SunPmTo'
        /// </summary>
        [Test]
        public void SunPmToTest()
        {
            // TODO unit test for the property 'SunPmTo'
        }
        /// <summary>
        /// Test the property 'ThuAmFrom'
        /// </summary>
        [Test]
        public void ThuAmFromTest()
        {
            // TODO unit test for the property 'ThuAmFrom'
        }
        /// <summary>
        /// Test the property 'ThuAmTo'
        /// </summary>
        [Test]
        public void ThuAmToTest()
        {
            // TODO unit test for the property 'ThuAmTo'
        }
        /// <summary>
        /// Test the property 'ThuPmFrom'
        /// </summary>
        [Test]
        public void ThuPmFromTest()
        {
            // TODO unit test for the property 'ThuPmFrom'
        }
        /// <summary>
        /// Test the property 'ThuPmTo'
        /// </summary>
        [Test]
        public void ThuPmToTest()
        {
            // TODO unit test for the property 'ThuPmTo'
        }
        /// <summary>
        /// Test the property 'TueAmFrom'
        /// </summary>
        [Test]
        public void TueAmFromTest()
        {
            // TODO unit test for the property 'TueAmFrom'
        }
        /// <summary>
        /// Test the property 'TueAmTo'
        /// </summary>
        [Test]
        public void TueAmToTest()
        {
            // TODO unit test for the property 'TueAmTo'
        }
        /// <summary>
        /// Test the property 'TuePmFrom'
        /// </summary>
        [Test]
        public void TuePmFromTest()
        {
            // TODO unit test for the property 'TuePmFrom'
        }
        /// <summary>
        /// Test the property 'TuePmTo'
        /// </summary>
        [Test]
        public void TuePmToTest()
        {
            // TODO unit test for the property 'TuePmTo'
        }
        /// <summary>
        /// Test the property 'WedAmFrom'
        /// </summary>
        [Test]
        public void WedAmFromTest()
        {
            // TODO unit test for the property 'WedAmFrom'
        }
        /// <summary>
        /// Test the property 'WedAmTo'
        /// </summary>
        [Test]
        public void WedAmToTest()
        {
            // TODO unit test for the property 'WedAmTo'
        }
        /// <summary>
        /// Test the property 'WedPmFrom'
        /// </summary>
        [Test]
        public void WedPmFromTest()
        {
            // TODO unit test for the property 'WedPmFrom'
        }
        /// <summary>
        /// Test the property 'WedPmTo'
        /// </summary>
        [Test]
        public void WedPmToTest()
        {
            // TODO unit test for the property 'WedPmTo'
        }

    }

}
